### ISSUE TITLE
persistent cache?

### ISSUE THREAD

**Issue by segator** [archiecobbs/s3backer#104]
If I mount s3backer on nodeA, after playing a while it generate lets say 100G of cache.
then umount s3backer on nodeA.

Execute in nodeB.
Lets say we play and get 50G of cache.
umount 
them mount again on nodeA.
Is cache of nodeA valid? I understand blocks that have been modified on nodeB will invalidate part of nodeA cache, but imagine nodeB only modify 2 little blocks, is the remaining nodeA cache valid? or s3backer will drop all the cache because detects was mounted elsewhere?

**Comment by archiecobbs** [comment]
Yes this will work; `s3backer` verifies cached blocks are still valid after a restart.

Some additional detail from the man page (see last paragraph below):

             By default, only clean cache blocks are recoverable after a restart.
             This means a system crash will cause dirty blocks in the cache to be
             lost (of course, that is the case with an in-memory cache as well).

             With the newer cache file format introduced in release 1.5.0, you can
             recover these dirty blocks by specifying the
             --blockCacheRecoverDirtyBlocks option.  This will cause any dirty
             blocks in the cache file to be made writable again on startup.  If
             your cache file was created with a prior release of s3backer or you do
             not specify this option, dirty blocks in the cache file are discarded
             on startup.  The window of this data loss can be limited by
             --blockCacheWriteDelay.

             By default, when having reloaded the cache from a cache file, s3backer
             will verify the MD5 checksum of each reloaded block with Amazon S3
             before its first use.  This verify operation does not require actually
             reading the block's data, and therefore is relatively quick.  This
             guards against the cached data having unknowingly gotten out of sync
             since the cache file was last used, a situation that is otherwise
             impossible for s3backer to detect.
