### ISSUE TITLE
why fuse instead of ISCSI?

### ISSUE THREAD

**Issue by segator** [archiecobbs/s3backer#105]
your idea to use object storage as a block device is awesome, but you create it through fuse, I think it will be easier to have iscsi interface and more portable, any posibility yo can be compatible with both?

**Comment by archiecobbs** [comment]
The original explicit goal of `s3backer` was to provide disk-like access Amazon S3 as simply as possible (hence the name).

Regarding iSCSI, not sure what you mean.  Are you talking about _using_ an iSCSI interface, or _providing_ an iSCSI interface?

**Comment by archiecobbs** [comment]
If that's what you want, then why not just configure the mounted `s3backer` file as a backstore?

https://www.rootusers.com/how-to-configure-an-iscsi-target-and-initiator-in-linux/

**Comment by segator** [comment]
Extra fuse layer that can be avoided ;)

**Comment by archiecobbs** [comment]
I'd would guess that the overhead of FUSE is orders of magnitude lower than the overhead of talking to Amazon over the Internet...
