### ISSUE TITLE
1.5.1 - only works in foreground

### ISSUE THREAD

**Issue by dentm42** [archiecobbs/s3backer#109]
I just installed version 1.5.1 on a new Centos 7 VPS and have run into a problem where it only works in foreground mode (or in debug mode) but never actually writes data to the back end (and will eventually hang operations) if it is in the normal background operation.

Since it seems to work fine in debug (and foreground), I'm kind of at a loss with regard to any sort of debugging to figure out what may be happening.

Any thoughts or help appreciated.

-- Matt

**Comment by dentm42** [comment]
Digging a bit further - it seems to do GET, it also PUTs the lock file in the S3 bucket.  But no other PUTs seem to happen except when the -f flag or the -d flag are present.   In stats, http_puts stays at 1 (again, unless -d or -f are present).

**Comment by archiecobbs** [comment]
When running in the background, are your mounts configured in `/etc/fstab` and is `systemd` running?

There is a [bug](https://github.com/systemd/systemd/issues/1741) in `systemd` several years old whereby it screws up loopback mounts.

**Comment by dentm42** [comment]
Looks like that's the likely culprit -- I'm in testing and am running everything at the command line.  Looking at the logging and symptoms - looks like the bug bit me.  Thanks for the quick response!  And DOUBLE thanks for a great tool!

**Comment by barula** [comment]
> When running in the background, are your mounts configured in `/etc/fstab` and is `systemd` running?
> 
> There is a [bug](https://github.com/systemd/systemd/issues/1741) in `systemd` several years old whereby it screws up loopback mounts.

Hi, great app!! can you tell me the workaround for this issue?

**Comment by archiecobbs** [comment]
There are actually two bugs... for the systemd bug, I don't know of a workaround, but you may be able to find one by researching it directly.

There was also bug #112 in s3backer which caused it to fail when run in the background. This bug was fixed in version 1.5.2. So at least make sure you're running s3backer >= 1.5.2 before doing any work related to the systemd bug.
