### ISSUE TITLE
Use against Minio

### ISSUE THREAD

**Issue by cbluth** [archiecobbs/s3backer#110]
is there a way to use this on top of minio?

**Comment by archiecobbs** [comment]
I'm not familiar with Minio. In theory if Minio is compatible with Amazon S3 it should work.

If you have problems I'd recommend contacting their technical support.

Related:
* Issue #96
* [This thread](https://groups.google.com/forum/#!msg/s3backer-devel/FW8MMpIYy8A/UM5VQFsjCgAJ)

**Comment by archiecobbs** [comment]
Issue #96 should be fixed now, and hopefully this issue as well.
