### ISSUE TITLE
Block cache workers don't work

### ISSUE THREAD

**Issue by daggaz** [archiecobbs/s3backer#112]
The change made in 0b0e908f25604bf0d608b386749d8a74c6ec2f8e (to initialize s3backer store in `main()` before calling `fuse_main()`) causes the block cache to fill up until dirty ratio = 1.

This is because the block cache worker threads are created pre-fork, and therefore cease to exist once `main()` exits.

Before `s3backer_create_store()` was called in `fuse_op_init()` (post-fork).

Threads do not survive `fork()`.

This also causes s3backer to hang indefinitely when shutting down, as it's waiting for threads to terminate that no longer exist.

**Comment by archiecobbs** [comment]
Bleh! I thought the problem was all due to issue #109 but you are correct, this pthread-after-fork() thing is also a problem.

Should be fixed in 78e2e78.
