### ISSUE TITLE
The server-side encryption header can't be set on DELETE requests?

### ISSUE THREAD

**Issue by apoliakov** [archiecobbs/s3backer#116]
Hello! Archie, this tool is awesome! Thanks for making it.

In some cases, we are using S3 Backer with the "server-side encryption" thing and what we're finding is that, apparently, the SSE header is not accepted on DELETE requests. When you do a DELETE with SSE, you get back a 400 (Bad Request) from s3. The fix seems to be simply to not set it on DELETE requests. You already follow a semi-pattern where some headers are "put-only" and it would appear the SSE header belongs in that bag.

You can see similar behavior with something like R. Note you get a 400 if you supply the header:
```R
#This fails
> s3HTTP(verb = "DELETE", bucket = 'XXXX',
+        path = paste0("/outgoing/P4_s3_test/foo"),
+        headers=(list('x-amz-server-side-encryption' = 'AES256')),
+        check_region = F)
Client error: (400) Bad Request
[1] FALSE

#This works
> s3HTTP(verb = "DELETE", bucket = 'XXXX',
+        path = paste0("/outgoing/P4_s3_test/foo"),
+        check_region = F)
[1] TRUE
```

What we see in S3 backer is a bit of a silent error. For example, when you unmount a bucket and it goes to clear the mount flag, you get this in the log:
```
... clearing mount token
2019-09-08 01:02:35 ERROR: rec'd 400 response: DELETE https://s3.amazonaws.com/XXX/s3backer-mounted
2019-09-08 01:02:36 INFO: retrying query (attempt #2): DELETE https://s3.amazonaws.com/XXX/s3backer-mounted
2019-09-08 01:02:36 ERROR: rec'd 400 response: DELETE https://s3.amazonaws.com/XXX/s3backer-mounted
2019-09-08 01:02:36 INFO: retrying query (attempt #3): DELETE https://s3.amazonaws.com/XXX/s3backer-mounted
```

And so it never succeeds in clearing the mounted flag, for example. We saw the same when trying to delete the actual disk blocks. And that's probably more insidious. But you can fail to notice it if you don't look at the log...

You set this header in two places. 
Here:
https://github.com/archiecobbs/s3backer/blob/d71f40e9657a091eac8920fd102b7683eaff4de7/http_io.c#L1039
And here:
https://github.com/archiecobbs/s3backer/blob/d71f40e9657a091eac8920fd102b7683eaff4de7/http_io.c#L1699

And our problems went away when we moved these if-blocks inside the "if PUT" cases above. Pretty trivial change.

Thanks again!

**Comment by archiecobbs** [comment]
Thanks! Fixed in 813ae24.
