### ISSUE TITLE
SSL in non US region without vhost

### ISSUE THREAD

**Issue by jeromerobert** [archiecobbs/s3backer#117]
I did not managed to make s3backer work in `eu-west-1` with SSL and vhost. I'm not sure to understand all issues but one obvious is that having a dot in a bucket name break wildcard certificates.  `*.s3.eu-west-1.amazonaws.com` does match `foo-bar.s3.eu-west-1.amazonaws.com` but not `foo.bar.s3.eu-west-1.amazonaws.com`.

Here is the command I use:
```
s3backer --size=500G --blockSize=1M --encrypt --compress=1 --accessEC2IAM=fee --region=eu-west-1 --ssl foo.bar /mnt/foobar
```

Here is the output with `--debug-http`:

```
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55f56a966950)
* Connected to foo.bar.s3-eu-west-1.amazonaws.com (52.218.80.107) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to foo.bar.s3-eu-west-1.amazonaws.com:443 
* Closing connection 1
```
If I disable vhost with  https://github.com/jeromerobert/s3backer/commit/0b46ff137db372c5ee8913b74781d1c3142d7080 it works.

`--region` enforce `--vhost` so there is currently no way to disable vhost without patching. Could we have a `--no-vhost` or do not enable vhost by default with SSL ?

**Comment by archiecobbs** [comment]
Added `--no-vhost` flag in ac2422d.

Let me know if this doesn't solve it for you.
