### ISSUE TITLE
SSL connect error after fork

### ISSUE THREAD

**Issue by jeromerobert** [archiecobbs/s3backer#118]
When I start s3backer this way it works properly:

```
s3backer -f --debug --debug-http --blockCacheSize=2048 --blockCacheFile=/var/cache/s3backer --encrypt --compress=1  --prefix=p/ --accessEC2IAM=xxxx --no-vhost --ssl --region=eu-west-1 foo.bar /mnt/
```

If I remove `-f` the mount operation work properly. It print some debug message showing that it successfully create the `s3backer-mounted` object. But when I run `more /mnt/file` it freeze and `/var/log/messages` is full:

```
s3backer: operation failed: SSL connect error (will retry)
s3backer: retrying query (attempt #2): GET https://s3-eu-west-1.amazonaws.com/foo.bar/p/00000000
```

**Comment by archiecobbs** [comment]
Might be a duplicate of issue #109. Please retry with release 1.5.4 if you're running an older version.

**Comment by jeromerobert** [comment]
I'm already using the current master (I need it for `--no-vhost`). I have that issue with RHEL 7, I'm going to test with Debian buster to see if this is distro dependent.

**Comment by jeromerobert** [comment]
No issue with Debian 10.1.

**Comment by jeromerobert** [comment]
I tried to monitor traffic with mitmproxy (as I cannot get `--debug-http` logs in detached mode). It works before the fork, but after, s3backer seems to ignore `https_proxy` and the traffic no longer go through mitmproxy. Using tcpdump I can see that s3backer is communicating with `s3-eu-west-1.amazonaws.com` but as it's SSL I cannot do any diagnostic.

**Comment by jeromerobert** [comment]
I modified s3backer to get curl logs in detached mode (see https://github.com/jeromerobert/s3backer/commit/5ba3b797ee9883733cb08997bcbb3c7434e46382). My log is full of messages like this:

```
* Connected to s3-eu-west-1.amazonaws.com (52.218.80.162) port 443 (#6)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -8023 (SEC_ERROR_PKCS11_DEVICE_ERROR)
* A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.
* Closing connection 6
```

**Comment by jeromerobert** [comment]
RHEL 7 curl is linked with NSS while s3backer is linked with OpenSSL. I will try to build a new curl linked with OpenSSL.

**Comment by jeromerobert** [comment]
Rebuilding curl with OpenSSL fixed the issue. Sorry for the noise.
