### ISSUE TITLE
Connect to S3 server with wildcard certificate fails

### ISSUE THREAD

**Issue by ravenpride** [archiecobbs/s3backer#120]
Hello,

I'm trying to connect to a Wasabi S3 server and encounter the following error:

```
*   Trying 130.117.252.11:443...
* TCP_NODELAY set
* Connected to <bucketname>.s3.eu-central-1.wasabisys.com (130.117.252.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=EssentialSSL Wildcard; CN=*.eu-central-1.wasabisys.com
*  start date: Jan 24 00:00:00 2019 GMT
*  expire date: Jan 23 23:59:59 2021 GMT
*  subjectAltName does not match <bucketname>.s3.eu-central-1.wasabisys.com
* SSL: no alternative certificate subject name matches target host name '<bucketname>.s3.eu-central-1.wasabisys.com'
```

If I interpret the log correctly, Wasabi uses a wildcard certificate for all bucket vhosts (`*.eu-central-1.wasabisys.com`) which is pretty ok. *s3backer* seems to check whether the FQDN is listed in the SAN list of that certificate. This check fails although the wildcard covers the checked FQDN.

Is there anything I could do to work around this issue?

Thank you in advance!

Best regards,
Sascha

**Comment by archiecobbs** [comment]
SSL certificate checking is performed in the OpenSSL library, not `s3backer`.

But in any case, OpenSSL is doing the right thing here: [wildcard certificates only match first level subdomains](https://stackoverflow.com/a/9743652/263801), but your domain`<bucket>.s3.eu-central-1.wasabisys.com` is a second-level subdomain of `eu-central-1.wasabisys.com`.

So either WasabiSys has their server misconfigured, or `s3backer` is sending the wrong URL.

**Comment by ravenpride** [comment]
It actually seems a configuration issue at Wasabi. Even worse is that my bucket name contains periods that would result in more subdomains. I'll have a closer look at it tomorrow.

Thank you for your help, now I know where I can dig a bit deeper!

**Comment by archiecobbs** [comment]
OK. I'll close this issue for now, but feel free to reopen if there's something `s3backer` needs to do better.
