### ISSUE TITLE
Segfault when creating s3b device

### ISSUE THREAD

**Issue by gesrat** [archiecobbs/s3backer#124]
I cloned latest source from Github and built on Ubuntu.  When I ran this command `/usr/bin/s3backer --blockSize=128K --size=1G  --region="us-west-2"  mybucket ~/mnt-mybucket` I got a segfault. After debugging with gdb, I discovered that the code change below (see comment section "GES start - GES end") needed to be made to s3b_config.c in order to ensure that this call `r = (*s3b->meta_data)(s3b, &auto_file_size, &auto_block_size);` on line 1368 or thereabouts would succeed, otherwise both values are null pointers.

```
    /*
     * Read the first block (if any) to determine existing file and block size,
     * and compare with configured sizes (if given).
     */
    if (config.test)
        config.no_auto_detect = 1;
    if (config.no_auto_detect)
        r = ENOENT;
    else {
        config.http_io.debug = config.debug;
        config.http_io.quiet = config.quiet;
        config.http_io.log = config.log;
        /* GES start */
        config.http_io.prefix = config.prefix;
        config.http_io.bucket = config.bucket;
        /* GES end */
        if ((s3b = http_io_create(&config.http_io)) == NULL)
            err(1, "http_io_create");
        if (!config.quiet)
            warnx("auto-detecting block size and total file size...");
        r = (*s3b->meta_data)(s3b, &auto_file_size, &auto_block_size);
        (*s3b->destroy)(s3b);
    }

```

**Comment by archiecobbs** [comment]
Thanks! Should be fixed in 427352c.
