### ISSUE TITLE
s3backer: can't list blocks: Operation not permitted

### ISSUE THREAD

**Issue by oracleloyall** [archiecobbs/s3backer#126]
When I change prefix path (S3BACKER_DEFAULT_PREFIX),it could not list blocks,programe called " The requested URL returned error: 403 Forbidden",how to solve this problem?

**Comment by archiecobbs** [comment]
A couple of questions...
* Why are you changing S3BACKER_DEFAULT_PREFIX instead of just using the `--prefix` flag (if that's indeed what you're doing)?
* What value are you changing it to? Perhaps it contains characters not supported by S3?

**Comment by oracleloyall** [comment]
> * --prefix

use --prefix and --listBlocks can use filesystem.When I use --prefix=test/ the GET http  prefix is "test%2F" call wrong.
When I use --prefix=test ,progame while loop " GET http://****.oss-cn-hangzhou-internal.aliyuncs.com/?marker=test00000000&max-keys=256&prefix=test"

**Comment by archiecobbs** [comment]
What version of s3backer are you using?

**Comment by oracleloyall** [comment]
> What version of s3backer are you using?

The trunk version.

**Comment by archiecobbs** [comment]
I think it may be that a `--prefix` containing a slash character is not allowed by the server.

When you omit the slash from the prefix, you say it "loops"... ? Are you sure it's not just reading the list of blocks as it normally does with `--listBlocks`?

**Comment by archiecobbs** [comment]
Commit 4825384f may help you debug this situation now.

```
commit 4825384fbfa6d8d8de0cf9a14f7b064650f5d1fc
Author: Archie L. Cobbs <archie.cobbs@gmail.com>
Date:   Wed May 26 19:07:49 2021 -0500

    Show HTTP error response payload content when `--debug-http' flag given.

```
