### ISSUE TITLE
Recent Release

### ISSUE THREAD

**Issue by aaruni96** [archiecobbs/s3backer#127]
The last release I can find is 1.5.4 from October 2019. The feature I'm looking for ( --blockCacheNumProtected ) was added after this release.

Are there any plans of adding a new release? I assume using a release is safer than building from the latest master in production.

**Comment by archiecobbs** [comment]
Building from `master` is safe.

Just make sure `autoconf`, `automake` are installed and then do the following:
```bash
$ ./cleanup.sh
$ ./autogen.sh
$ ./configure
$ make distcheck
```
then you should have a tarball named `s3backer-1.5.4.tar.gz` which you can build normally.

**Comment by aaruni96** [comment]
What's the recommended method of updating an existing install ?

**Comment by archiecobbs** [comment]
You can simply overwrite it. Just `./configure && make && sudo make install` from within the build directory after unpacking.

**Comment by aaruni96** [comment]
Thanks a bunch!
