### ISSUE TITLE
Use bucket "directories" instead of prefix

### ISSUE THREAD

**Issue by akamensky** [archiecobbs/s3backer#130]
Using prefix requires knowing it ahead of time. Which might not be the case or a bit of a hustle to do. Most of S3 implementations support directories. I think it would be great to be able to use `bucket/directory` in mounting options. This would also open a possibility for listing all available "disks" and keep structure cleaner.

Upsides:

* cleaner structure w/o files from same "disk" being mixed in one pot
* ability to list available "disks" w/o needing to know them ahead of time (this could also be achieved using metadata file of some sorts in the root of bucket)

Downsides: I don't really see any other than time spent implementing this.

**Comment by archiecobbs** [comment]
Nice idea. Check out 9aa82ec and see if that works (I have not tested it myself yet).

**Comment by archiecobbs** [comment]
Fixed in 9aa82ec.
