### ISSUE TITLE
s3backer: http_io_create: No such file or directory

### ISSUE THREAD

**Issue by Kirin-kun** [archiecobbs/s3backer#136]
Hello,

Less of an issue, but more of a remark.

When the instance role (or the credentials ?) is wrong, s3backer fails with a cryptic message about : s3backer: http_io_create: No such file or directory.

I had mispelled the role in the configuration file and I was stumped for a while about what it was failing to "create".

Other than that, thank you for this wonderful piece of software. :love_you_gesture:

**Comment by archiecobbs** [comment]
Thanks, fixed in ee84d02.
