### ISSUE TITLE
Trim and cache file usage

### ISSUE THREAD

**Issue by Kirin-kun** [archiecobbs/s3backer#139]
After some successful use, I tested again the trimming of the zfs filsystem and it seems to work, but it's stressing the partition where the cache file resides a lot.

I did an iostat -x 5 -p during the trim, and I typically have something like:

```
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
xvda              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdap1            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdap2            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdb              0.00     0.00    0.00 1184.00     0.00 122240.50   206.49     3.41    2.88    0.00    2.88   0.76  90.54
xvdbp1            0.00     0.00    0.00 1183.00     0.00 122240.00   206.66     3.40    2.88    0.00    2.88   0.77  90.54
xvdbp2            0.00     0.00    0.00    1.00     0.00     0.50     1.00     0.00    3.60    0.00    3.60   3.60   0.36
xvdbp3            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
```

p1 is a partition I dedicated to the cache file.

This filsystem is actually practically empty: there's 4/5Gb of data and some of it has been deleted.

I started s3backer with --listBlocks, so the stats file typically looks like this after trimming a while:

```
http_normal_blocks_read      45
http_normal_blocks_written   26
http_zero_blocks_read        0
http_zero_blocks_written     0
http_empty_blocks_read       6
http_empty_blocks_written    106422
http_gets                    49
http_puts                    27
http_deletes                 0
http_avg_get_time            0.080 sec
http_avg_put_time            1.385 sec
http_avg_delete_time         0.000 sec
```

As expected, it doesn't send any DELETE, since the trimming is "wiping" non existent blocks and s3backer knows that.

But why is it thrashing the cache file so much ? 

Is it caching empty blocks ? Is there any way to avoid this ?

I want to trim my filesystem from time to time, but it's slowing the i/o to a crawl, even though it actually does nothing. And it becomes too slow to ever complete.

**Comment by archiecobbs** [comment]
It's probably all the synchronous writes to the disk cache. These are done to ensure consistency after a crash.

Try rebuilding with this patch and seeing if the problem goes away:

```patch
diff --git a/dcache.c b/dcache.c
index d3fa7b3..e96f0fb 100644
--- a/dcache.c
+++ b/dcache.c
@@ -551,6 +551,7 @@ s3b_dcache_write_block(struct s3b_dcache *priv, u_int dslot, const void *src, u_
 int
 s3b_dcache_fsync(struct s3b_dcache *priv)
 {
+/*
     int r;
 
 #if HAVE_DECL_FDATASYNC
@@ -562,6 +563,7 @@ s3b_dcache_fsync(struct s3b_dcache *priv)
         r = errno;
         (*priv->log)(LOG_ERR, "error fsync'ing cache file `%s': %s", priv->filename, strerror(r));
     }
+*/
     return 0;
 }
 
```

**Comment by Kirin-kun** [comment]
Doesn't look like it. It's just commenting the content of the s3b_dcache_fsync function, right ?

Same thing. 100%util of the partition:

```
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
xvda              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdap1            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdap2            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdb              0.00     0.00    0.00  955.60     0.00 122291.30   255.95   143.29  149.94    0.00  149.94   1.05 100.00
xvdbp1            0.00     0.00    0.00  955.40     0.00 122291.20   256.00   142.30  148.92    0.00  148.92   1.05 100.00
xvdbp2            0.00     0.00    0.00    0.20     0.00     0.10     1.00     0.99 5033.00    0.00 5033.00 4942.00  98.84
xvdbp3            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

```

**Comment by aaruni96** [comment]
Quickly chiming in to say that the problem also happens on btrfs and ext4.

Every time you call s3backer and try to TRIM, it will trim the entire capacity, and will completely max out the cache file in the process.

If you have the s3backer fs mounted for a long while, and already trimmed it once, subsequent TRIMs behave as expected.

**Comment by Kirin-kun** [comment]
Well, if the filsystem is large (in the TBs), then the trim would last several days, making it unusable. 

And each time you restart s3backer, it would walk the entire capacity again for a trim ?

I don't understand what it's doing. 

The filesystem obviously tells it to write "empty blocks" and s3backer doesn't send DELETE for non existing blocks. But it stills  caches something ?

**Comment by archiecobbs** [comment]
Hmm. I'll have to take a closer look when time permits.

**Comment by archiecobbs** [comment]
I think what's happening is that the block cache, being much smaller than the entire disk, is only able to "remember" any information about a small fraction of the entire disk's blocks, and, in particular, that information includes whether that block is deleted or not.

Note the block cache has no connection to `--listBlocks`, which instead operates at the (lower) HTTP layer.

So a fix would be:
- Include a (complete) bitmap in the block cache, dedicated to remembering deleted blocks
- Initialize that bitmap from `--listBlocks`, if any

**Comment by Kirin-kun** [comment]
Thank you for investigating this. It would be a huge improvement, both in term of performance and costs, for filesystems supporting trimming, allowing to reclaim space in the bucket more thoroughly.

zfs has an on-the-fly trim feature, but it doesn't delete small block ranges, so there's value in walking the blockmap to delete additional blocks. Obviously, it's the same for other filesystems, like btrfs and xfs.

I made a 20TB virtual filesystem and if I try to trim it, as the cache partition is slowing everything to a crawl, the server becomes unusable.

For the records, I've been tasked to lower our AWS costs and to replace, if possible, some EBS storage by s3 storage for data that don't really demand good performance (a kind of nas storage), and s3backer checks almost all the requirements (and you even quickly added the encryption features I needed, on top of correcting some bugs!). Alternatives are either lacking some filesystem features (likes permissions or hardlinks), or are highly priced (ObjectiveFS...). And since I'm familiar with zfs, it's the cherry on the top to be able to use it.

**Comment by archiecobbs** [comment]
Thanks for your good bug reports. Please try 034fff3 which should hopefully address this.

**Comment by Kirin-kun** [comment]
Sorry, for the delay. I tested and I didn't see any difference. There's still a heavy load on the cache partition:

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.03    0.00    0.78   23.78    0.05   75.36

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
xvda              0.00     0.00    0.00    0.60     0.00     2.70     9.00     0.00    1.33    0.00    1.33   1.33   0.08
xvdap1            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
xvdap2            0.00     0.00    0.00    0.60     0.00     2.70     9.00     0.00    1.33    0.00    1.33   1.33   0.08
xvdb              0.00     0.00    0.00 1100.40     0.00 122286.50   222.26     3.80    3.45    0.00    3.45   0.86  94.34
xvdbp1            0.00     0.00    0.00 1099.40     0.00 122286.00   222.46     3.80    3.45    0.00    3.45   0.86  94.34
xvdbp2            0.00     0.00    0.00    1.00     0.00     0.50     1.00     0.00    2.40    0.00    2.40   2.40   0.24
xvdbp3            0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

```

High load:

```
#  uptime
 18:06:32 up 4 days,  3:48,  2 users,  load average: 10.77, 6.16, 2.61
```

And stats, during trimming:

```
http_normal_blocks_read      65
http_normal_blocks_written   13
http_zero_blocks_read        0
http_zero_blocks_written     2
http_empty_blocks_read       110
http_empty_blocks_written    50917
http_gets                    68
http_puts                    14
http_deletes                 2
http_avg_get_time            0.108 sec
http_avg_put_time            3.719 sec
http_avg_delete_time         0.063 sec
http_unauthorized            0
http_forbidden               0
http_stale                   0
http_verified                32
http_mismatch                0
http_5xx_error               0
http_4xx_error               0
http_other_error             0
http_canceled_writes         84
http_num_retries             0
http_total_retry_delay       0.000 sec
curl_handle_reuse_ratio      0.4179
curl_timeouts                0
curl_connect_failed          0
curl_host_unknown            0
curl_out_of_memory           0
curl_other_error             0
block_cache_current_size     16000 blocks
block_cache_initial_size     16000 blocks
block_cache_dirty_ratio      0.9994
block_cache_read_hits        1897
block_cache_read_misses      175
block_cache_read_hit_ratio   0.9155
block_cache_write_hits       1372
block_cache_write_misses     66882
block_cache_write_hit_ratio  0.0201
block_cache_verified         32
block_cache_mismatch         0
zero_block_cache_size        66974 blocks
zero_block_cache_read_hits   103
zero_block_cache_write_hits  208
md5_cache_current_size       6536 blocks
md5_cache_data_hits          0
md5_cache_full_delays        0.000 sec
md5_cache_write_delays       4758.866 sec
out_of_memory_errors         0
```

It doesn't seem to hit the zero block cache very often?

The "zero_block_cache_size" is growing, as it detects more "empty blocks", but since I started with --listBlocks, I'd think it would be initialized?

**Comment by archiecobbs** [comment]
OK I think there's one more piece to this...

> The "zero_block_cache_size" is growing, as it detects more "empty blocks", but since I started with --listBlocks, I'd think it would be initialized?

The zero block cache is not initialized directly from `--listBlocks` because they are on opposite sides of the block cache and therefore the information could differ. For example, `--listBlocks` might report a block as deleted in S3, but the block cache might be holding onto a dirty, non-zero version of that block that is waiting to be written back.

However, the zero cache will quickly learn about deleted blocks (without any network I/O) as they are read, so this is not a problem... except that these reads will still be going through the block cache, which is the original problem we're trying to avoid.

So I think the remaining piece is that the zero cache does need to be initialized from `--listBlocks`, but only for those blocks that are not also sitting in a recovered block cache.

This should be easy, stand by...

**Comment by Kirin-kun** [comment]
Well, the reads don't seem to be the problem, but the writes, if I look at the iostat.

**Comment by ahmgithubahm** [comment]
> For the records, I've been tasked to lower our AWS costs and to replace, if possible, some EBS storage by s3 storage for data that don't really demand good performance (a kind of nas storage), and s3backer checks almost all the requirements (and you even quickly added the encryption features I needed, on top of correcting some bugs!). Alternatives are either lacking some filesystem features (likes permissions or hardlinks), or are highly priced (ObjectiveFS...). And since I'm familiar with zfs, it's the cherry on the top to be able to use it.

I agree that using ZFS in s3backer is great, but also thought I'd point out that, depending what S3 storage class you're using to host s3backer, and how much you care about your data (!), the pricing for the cheapest sc1 EBS volumes is actually lower than S3!

In eu-west-2:
S3 standard - $0.024 per GB per month (for first 50 TB), plus request pricing
EBS sc1 (Cold HDD) volumes - $0.0174 per GB per month

This ignores the costs of EBS snapshots, however, which are pretty much essential of course.

**Comment by Kirin-kun** [comment]
And this also ignores the fact that HDDs are not "thin" volumes. 

Ie, if you add a 4TBs sc1 to your instance, you pay for the 4TBs, whether they are effectively used or not.

That's also why the fact that s3backer is a sparse "volume" is a big plus.

**Comment by Kirin-kun** [comment]
Also, ZFS is ideal, because with L2ARC cache and SLOG on SSD the "slowness" of the backend is mitigated. 

The "xvdb" up there is a gp2 I dedicated to l2arc, slog and s3backer cache. In normal operations, the s3 volumes is indistinguishable from a real disk.

**Comment by archiecobbs** [comment]
@Kirin-kun , please try 196ead1 now. Thanks.

**Comment by aaruni96** [comment]
At least for me (on btrfs), the latest commit seems to have solved the issue.

**Comment by Kirin-kun** [comment]
I can confirm that the latest commit seems to have corrected the problem.

The trim is running:
```

http_normal_blocks_read      9028
http_normal_blocks_written   8259
http_zero_blocks_read        0
http_zero_blocks_written     26085
http_empty_blocks_read       4
http_empty_blocks_written    0
http_gets                    9034
http_puts                    8260
http_deletes                 26085
http_avg_get_time            0.116 sec
http_avg_put_time            0.159 sec
http_avg_delete_time         0.021 sec
http_unauthorized            0
http_forbidden               0
http_stale                   0
http_verified                298
http_mismatch                0
http_5xx_error               1
http_4xx_error               0
http_other_error             0
http_canceled_writes         264
http_num_retries             1
http_total_retry_delay       10.000 sec
curl_handle_reuse_ratio      0.9871
curl_timeouts                0
curl_connect_failed          0
curl_host_unknown            0
curl_out_of_memory           0
curl_other_error             0
block_cache_current_size     17000 blocks
block_cache_initial_size     17000 blocks
block_cache_dirty_ratio      0.1593
block_cache_read_hits        42947
block_cache_read_misses      8856
block_cache_read_hit_ratio   0.8290
block_cache_write_hits       45784
block_cache_write_misses     28551
block_cache_write_hit_ratio  0.6159
block_cache_verified         298
block_cache_mismatch         0
zero_block_cache_size        28654 blocks
zero_block_cache_read_hits   12882
zero_block_cache_write_hits  863378
md5_cache_current_size       1301 blocks
md5_cache_data_hits          0
md5_cache_full_delays        0.000 sec
md5_cache_write_delays       25342.622 sec
out_of_memory_errors         0
```

It seems to give some spikes of load/io only when meeting previously non-empty blocks that have to be emptied. 

But it's incomparably faster than before!

Thanks for fixing this issue. It's a huge help!

**Comment by Kirin-kun** [comment]
Just a question: is the zero block cache persistent in the cache file? And is it used if the option --listBlocks isn't present?

When there are a lot of blocks, the --listBlocks take a very long time.

If you stop and restart s3backer without the --listBlocks, it's much faster, but does it still benefit from a persistent zero cache file (provided the cache file is still there, of course), or do you have to systematically add the parameter if you plan to trim your filesystem?

**Comment by ahmgithubahm** [comment]
Great news that this behaviour is being improved!  @Kirin-kun have you or could publicise your set up and settings for best use of s3backer for hosting ZFS vdevs?  Thanks

**Comment by archiecobbs** [comment]
Glad it's working!

To summarize the basic problem, before this change we were not making full use of the information retrieved by `--listBlocks`. As a result, writes of zero blocks were being stored in the block cache (instead of being ignored as could be), causing a bunch of churn there during heavy "zeroing" operations like fstrim.

> Just a question: is the zero block cache persistent in the cache file? And is it used if the option --listBlocks isn't present?

It's not persisted in the cache file, and so it's not going to provide nearly as much benefit without `--listBlocks`. More precisely, right after startup it will provide no additional benefit, but after you've visited all the zero blocks (and thus fully primed the zero cache), it would provide the same benefit. So e.g., a first fstrim would be slow, but any additional fstrim's would be fast. Obviously the first one is usually the one that matters :)

Including the zero blocks in the persistent cache file would be a next step, though of course this would re-introduce the need for disk I/O during an fstrim (though presumably much less than before).
