### ISSUE TITLE
Recommended Updating Method

### ISSUE THREAD

**Issue by aaruni96** [archiecobbs/s3backer#142]
I understand I can update s3backer by just running pulling in the fresh master, and making it, letting it overwrite the old files.

But I assume the running s3backer instances are still the old versions. Is there a way to "inplace" upgrade those instead of having to unmount the drives, and then remounting?

I'd like to avoid the kind of downtime it takes to stop the services accessing the drives, unmount and mount again ~15 s3backer volumes, and then restart the services.

**Comment by archiecobbs** [comment]
There's no way to do that, sorry...

**Comment by aaruni96** [comment]
Is it a feature that could possible be added in a future release?

Since blockCaches are involved, I think there should be a way to tell the s3backer process to restart, and then recover the local data it takes in the few seconds to restart ?

If not, you can just close this issue.

**Comment by archiecobbs** [comment]
The problem is not the block cache, it's all the other internal program state, including the FUSE mount. Unfortunately with C programs there's no easy way to save and restore this state. I agree, it would be nice though :)
