### ISSUE TITLE
Write objects to local directory

### ISSUE THREAD

**Issue by aaruni96** [archiecobbs/s3backer#143]
I have a use case where it would be helpful to read/write the objects used by s3backer into a local directory. (so, something like taking backup of the bucket on a USB drive).

Is this possible to achieve ?

**Comment by archiecobbs** [comment]
I think so... see https://stackoverflow.com/questions/8659382/downloading-an-entire-s3-bucket

**Comment by aaruni96** [comment]
Sorry for reopening, but I meant for a way to do it from within s3backer.

Something like

`s3backer --blockSize=128k --size=100G --compress --encrypt=aes-256-cbc --listBlocks --local s3backer-local/ s3-b/`

Then I would want the objects which are normally sent over http to the directory s3backer-local/ instead.

**Comment by archiecobbs** [comment]
Sorry, I'm still missing something...

It sounds like you just want to copy all the objects to/from/between S3 and a local directory... in which case the s3cmd utility will work. How is what you're asking different from that?

On the other hand, if you just want to use a local directory as a "backend" instead of S3, the `test_io` layer can do that.

**Comment by aaruni96** [comment]
Reading the wiki, `--test` is what I thought would be the perfect fit for me, but it did not work as expected.

The exact command I ran was 

`sudo s3backer --blockSize=128k --size=106G --compress --encrypt=aes-256-cbc --listBlocks --test s3backer-local/ s3-b/`

I was then able to `mkfs.btrfs s3-b/file` and also `mount -o loop s3-b/file mountdir`, as normal, and copied some data into it.

But I do not see anything being actually written into the directory s3backer-local.

Additionally, `sudo umount mountdir hangs indefinitely.

**Comment by archiecobbs** [comment]
The `--test` flag may be broken, as I haven't used it myself in a long time.

I'll investigate...

**Comment by archiecobbs** [comment]
Hmm. "Works for me".

Here's what I did.

First, create `s3backer-testio.conf`:

```
--blockSize=128k
--size=106G

--compress
--encrypt=aes-256-cbc

-f
#--debug

--listBlocks

--test

# Directory & mount point
testdir
mnt1
```

Next setup directories:

```
$ mkdir mnt1
$ mkdir testio
```

Then run `s3backer` in one shell window and create the filesystem in the other.

Here's a log from shell window 1:

```
$ ./s3backer -F s3backer-testio.conf 
Password: 
s3backer: auto-detection disabled; using configured block size 128k and file size 106g
s3backer: listing non-zero blocks...done
s3backer: found 0 non-zero blocks
2021-01-09 14:04:50 INFO: established new mount token 0x76bcced5
2021-01-09 14:04:50 INFO: s3backer process 29294 for mnt1 started
2021-01-09 14:04:50 INFO: mounting mnt1
2021-01-09 14:05:05 INFO: unmount mnt1: initiated
2021-01-09 14:05:05 INFO: unmount mnt1: flushing dirty data
2021-01-09 14:05:05 INFO: unmount mnt1: clearing mount token
2021-01-09 14:05:05 INFO: unmount mnt1: completed
$ 
```

And window 2:

```
$ mkfs.ext4 -E nodiscard mnt1/file 
mke2fs 1.43.8 (1-Jan-2018)
Creating filesystem with 27787264 4k blocks and 6946816 inodes
Filesystem UUID: a88732fa-c0b3-41cc-8ba6-55d73ff556e0
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000, 7962624, 11239424, 20480000, 23887872

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (131072 blocks): done
Writing superblocks and filesystem accounting information: done   

$ umount mnt1
$ ls testdir/
00000000  00000008  00000010  00000018  00000020  00004000  00014400  00030000  0004c000  00068000  00084000  000a0000  000bc000
00000001  00000009  00000011  00000019  00000021  00006400  00018000  00034000  00050000  00068400  00088000  000a4000  000c0000
00000002  0000000a  00000012  0000001a  00000121  00006c00  0001c000  00038000  00054000  0006c000  0008c000  000a8000  000c4000
00000003  0000000b  00000013  0000001b  00000400  00008000  0001f400  0003c000  00055c00  00070000  00090000  000ac000  000c8000
00000004  0000000c  00000014  0000001c  00000c00  0000c000  00020000  0003cc00  00058000  00074000  00094000  000b0000  000cc000
00000005  0000000d  00000015  0000001d  00001400  0000c400  00024000  00040000  0005c000  00078000  00098000  000b4000  000d0000
00000006  0000000e  00000016  0000001e  00001c00  00010000  00028000  00044000  00060000  0007c000  0009c000  000b6400
00000007  0000000f  00000017  0000001f  00002400  00014000  0002c000  00048000  00064000  00080000  0009c400  000b8000
$ 
```

**Comment by aaruni96** [comment]
I think I found the problem

Without the `-f` flag, s3backer resolves the local backing store from root (from the wiki). But there was no folder `/s3backer-local`. It was `~/s3backer-local`.

Probably s3backer just assumes whatever folder is given already exists, and then makes a bunch of invalid writes if that folder does not exist in reality.

**Comment by archiecobbs** [comment]
OK that makes sense. Like any other system process, if/when it becomes a daemon it changes current working directory to root.

But if that happens, `s3backer` should fail to even start:

```
$ rm -rf testdir
$./s3backer -F s3backer-testio.conf
s3backer: testdir: Not a directory
$ 
```

For me the above failure happens even without the `-f` flag:

```
$ ./s3backer --blockSize=128k --size=106G --compress --encrypt=aes-256-cbc --listBlocks --test testdir mnt1
s3backer: testdir: No such file or directory
```

Not sure what happened in your case.

**Comment by aaruni96** [comment]
I figured it out I think.

If you delete the directory, the check works fine. But if the directory exists, the test (presumably running in shell mode) finds it, and continues on. Later on, when the application is no longer in foreground and actually operating, everything is directed to an invalid location.

**Comment by archiecobbs** [comment]
Ah, that makes sense. Should be easy to fix.

**Comment by archiecobbs** [comment]
Should be fixed (actually, relative pathnames disallowed) in 467e507.
