### ISSUE TITLE
fstab fuse unknown options

### ISSUE THREAD

**Issue by khumarahn** [archiecobbs/s3backer#145]
Hi. Amazing program.

I get a fuse error when I place my mount in `fstab`. Mounting manually from the command line works fine. Wonder if it is a known thing, or if I'm going something wrong.

in `fstab`:
```
bucket/subfolder /mnt/s3 fuse.s3backer _netdev,force,size=100G,blocksize=1M,passwordFile=/etc/s3-key,encrypt,accessFile=/etc/s3-passwd,baseURL=https://some-bucket.url/,region=my-region,blockCacheFile=/mnt/s3.cache,blockCacheSize=256 0 0
```
```
# mount /mnt/s3
s3backer: auto-detecting block size and total file size...
s3backer: auto-detected block size=1m and total size=100g
s3backer: warning: filesystem appears already mounted but you said `--force'
 so I'll proceed anyway even though your data may get corrupted.

fuse: unknown option `blocksize=1M'
```

I'm on gentoo, using systemd 247.2, fuse 3.9.3 and s3backer 1.6.1.

**Comment by archiecobbs** [comment]
Options are case sensitive. Try `blockSize` instead of `blocksize`...

**Comment by khumarahn** [comment]
ah, that worked. Thanks! I feel stupid: I checked the options a number of times! Closing!
