### ISSUE TITLE
RAID?

### ISSUE THREAD

**Issue by brianmingus2** [archiecobbs/s3backer#150]
Can you create a RAID 0 atop S3 using s3backer mounts?

**Comment by archiecobbs** [comment]
Sure you could... assuming whatever RAID tool you're using can function on top of a regular file (or if not, then use `losetup(8)`).

I think the more interesting question is whether this would provide any performance benefit vs. a single mount that has multi-threaded caching enabled.

If you do any performance testing to compare various scenarios post them to the discussion group.
