### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the priv->mutex

### ISSUE THREAD

**Issue by ycaibb** [archiecobbs/s3backer#152]
Hi, developers, thank you for your checking. It seems the lock `priv->mutex` is not released correctly when `priv->num_threads == 0` in the function `block_cache_read`?
https://github.com/archiecobbs/s3backer/blob/016c3fe69760b6a0b03193e218b19488fa0862e8/block_cache.c#L617-L624

**Comment by ycaibb** [comment]
Similarly, the lock `&priv->mutex` is also not released in the `block_cache_do_read`, thank you very much for your checking.
https://github.com/archiecobbs/s3backer/blob/016c3fe69760b6a0b03193e218b19488fa0862e8/block_cache.c#L753-L771

**Comment by archiecobbs** [comment]
Your first comment is correct - thanks! Fixed in bee054a.

Your second comment is incorrect: the semantics of this function `block_cache_do_read()` are that the mutex is assumed to be (already) held at function entry and exit.

**Comment by ycaibb** [comment]
@archiecobbs Thank you very much.
