### ISSUE TITLE
Performance reduced since 1.6.0

### ISSUE THREAD

**Issue by semhoun** [archiecobbs/s3backer#158]
I started to used s3backer with the official debian bullseye package, and after I upgrade to the last version. I see a difference of speed between this two version. I do some test and finaly i foud when the performance was reduced. It's between version 1.5.6 and 1.6.0.

For my inital tests with ext4, i copy 248 files with a total size of 1.58 GiB. version 1.6.0 and 1.6.3 take 11mn to make the transfer and version 1.5.6 only used 3mn. I do a umount after the copy to be sure that everything seem written and i remove the cache and all files in bucket before each test. I also try with ext4 and reiserfs the result was the same, i also try different block size no amelioration.

This is the command line I used:

```
s3backer \
	--listBlocks \
	--blockSize=1m \
	--size=32g \
	--blockCacheFile=/opt/cloud/bucket/blockCacheFile \
	--encrypt \
	--passwordFile=/opt/cloud/bucket/passwordFile \
	--accessFile=/opt/cloud/bucket/accessFile \
	--baseURL=https://s3.nl-ams.scw.cloud/ \
	--region=nl-ams \
	bucket \
	/opt/cloud/bucket/s3backer
```

**Comment by archiecobbs** [comment]
Hmm, interesting.

There are a lot of variables here so the first thing to do would be to start narrowing things down and creating as simple a test case as possible

For example:
* Try eliminating the `--blockCacheFile` and/or `--encrypt`
* Instead of mounting an ext4 filesystem, try writing a bunch of random data, e.g.:
```bash
dd if=/dev/urandom of=/opt/cloud/bucket/s3backer/file bs=1048576 count=1000
```

**Comment by semhoun** [comment]
I do the tests you ask, this is the results:
_No Cache/No Encrypt_
1.6.0: 234 s, 4.5 MB/s
1.5.3: 47 s, 22.3 MB/s

_No Cache/With Encrypt_
1.6.0: 266 s, 3.9 MB/s
1.5.3: 94 s, 11.1 MB/s

_With Cache/No Encrypt_
1.6.0: 472 s, 2.2 MB/s
1.5.3: 70 s, 14.9 MB/s

_With Cache/With Encrypt_
1.6.0: 479 s, 2.2 MB/s
1.5.3: 100.903 s, 10.4 MB/s

The server I used for the test is a Intel Atom C2338 (2) @ 2.100GHz with ssd disk (it's my personnal dev server for C++ or php project). I will do the same tests on a my production (more powerfull) server. For the "lan" parts i'm on the same datacenter than the scaleway S3 Object Storage.

**Comment by semhoun** [comment]
I do the same tests with a more powerfull server (Intel Xeon D-1531 (12) @ 2.700GHz, the new results are:
_No Cache/No Encrypt_
1.6.0: 136 s, 7.7 MB/s
1.5.6: 14 s, 71.8 MB/s

_No Cache/With Encrypt_
1.6.0: 129 s, 8.1 MB/s
1.5.6: 14 s, 73.6 MB/s

_With Cache/No Encrypt_
1.6.0: 476 s, 2.2 MB/s
1.5.6: 49 s, 21.3 MB/s

_With Cache/With Encrypt_
1.6.0: 491 s, 2.1 MB/s
1.5.6: 36 s, 28.9 MB/s

**Comment by semhoun** [comment]
I compare the code between version 1.5.6 and 1.6.0, and maybe I found the cause of the poor performance. I removed the zero_cache_store creation in s3b_config.c and I get back the performance.

**Comment by archiecobbs** [comment]
Thanks for the test results. Sounds like there may be some problem with the zero_cache doing excessive locking. I'll take a look.

**Comment by archiecobbs** [comment]
Does anything change if you run the test on both versions but without the `--listBlocks` flag?

I'm wondering if the zero block survey, which now runs in the background after startup (instead of delaying startup as before) is somehow slowing things down.

**Comment by semhoun** [comment]
This the results of the new tests, I do it 2 times each to be sure:
_No listBlocks / No Cache/No Encrypt_
1.6.0: 243.313 s, 4.3 MB/s
1.5.6: 124 s, 8.4 MB/s

_With listBlocks / No Cache/No Encrypt_
1.6.0: 229.804 s, 4.6 MB/
1.5.6: 46 s, 22.5 MB/s

**Comment by archiecobbs** [comment]
Hmm. I'm actually seeing the reverse situation, where the current version is faster than 1.5.6.

Here's my setup:

`erase.conf`:
```
--accessFile=test1.creds
--blockSize=256k
--size=10G
--timeout=30
-f
--erase
```
`test.conf`:
```
--accessFile=test1.creds
--blockSize=256k
--size=10G
--timeout=30
-f
archie-test/test1
mnt1
```

**Testing with version 1.5.6**

Window 1:
```
$ ./s3backer-1.5.6 --version
s3backer version 1.5.6 (1.5.6)
Copyright (C) 2008-2020 Archie L. Cobbs.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ ./s3backer-1.5.6 -F reset.conf 
s3backer-1.5.6: auto-detecting block size and total file size...
s3backer-1.5.6: auto-detected block size=256k and total size=10g
s3backer-1.5.6: `--erase' flag given: erasing all blocks in http://s3.amazonaws.com/archie-test/test1/
s3backer: is this correct? [y/N] y
s3backer: erasing non-zero blocks..........done
s3backer-1.5.6: erased 1922 non-zero blocks
$ sudo ./s3backer-1.5.6 -F test.conf 
s3backer-1.5.6: auto-detecting block size and total file size...
s3backer-1.5.6: auto-detection failed; using configured block size 256k and file size 10g
2022-01-10 09:39:30 INFO: established new mount token 0x7e65492d
2022-01-10 09:39:30 INFO: s3backer process 23041 for mnt1 started
2022-01-10 09:39:30 INFO: mounting mnt1
^C
2022-01-10 09:41:31 INFO: unmount mnt1: initiated
2022-01-10 09:41:31 INFO: unmount mnt1: flushing dirty data
2022-01-10 09:41:31 INFO: unmount mnt1: clearing mount token
2022-01-10 09:41:31 INFO: unmount mnt1: completed
```
Window 2:
```
$ sudo time dd if=/home/archie/DellRoadTour.mp4 of=mnt1/file bs=256K status=progress
501481472 bytes (501 MB, 478 MiB) copied, 87 s, 5.8 MB/s
1921+1 records in
1921+1 records out
503787611 bytes (504 MB, 480 MiB) copied, 87.4146 s, 5.8 MB/s
0.01user 0.87system 1:27.41elapsed 1%CPU (0avgtext+0avgdata 2344maxresident)k
```

**Testing with current `master` branch**

Window 1:
```
$ ./s3backer-head --version
s3backer version 1.6.3 (1.6.3-3-g8c0b12c)
Copyright (C) 2008-2020 Archie L. Cobbs.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ ./s3backer-head -F reset.conf 
s3backer-head: auto-detecting block size and total file size...
s3backer-head: auto-detected block size=256k and total size=10g
s3backer-head: `--erase' flag given: erasing all blocks in http://s3.amazonaws.com/archie-test/test1/
s3backer: is this correct? [y/N] y
s3backer: erasing non-zero blocks..........done
s3backer-head: erased 1922 non-zero blocks
$ sudo ./s3backer-head -F test.conf 
s3backer-head: auto-detecting block size and total file size...
s3backer-head: auto-detection failed; using configured block size 256k and file size 10g
2022-01-10 09:41:55 INFO: established new mount token 0x182a3c2a
2022-01-10 09:41:55 INFO: s3backer process 22115 for mnt1 started
2022-01-10 09:41:55 INFO: mounting mnt1
^C
2022-01-10 09:43:29 INFO: unmount mnt1: initiated
2022-01-10 09:43:29 INFO: unmount mnt1: shutting down filesystem
2022-01-10 09:43:29 INFO: unmount mnt1: clearing mount token
2022-01-10 09:43:29 INFO: unmount mnt1: completed
```
Window 2:
```
$ sudo time dd if=/home/archie/DellRoadTour.mp4 of=mnt1/file bs=256K status=progress
488374272 bytes (488 MB, 466 MiB) copied, 27 s, 18.1 MB/s
1921+1 records in
1921+1 records out
503787611 bytes (504 MB, 480 MiB) copied, 27.8566 s, 18.1 MB/s
0.00user 1.04system 0:27.85elapsed 3%CPU (0avgtext+0avgdata 2316maxresident)k
684336inputs+0outputs (0major+159minor)pagefaults 0swaps
```

Results:
* Version 1.5.6 - 5.8 MB/s elapsed time 1:27
* Version from `master` - 18.1 MB/s elapsed time 0:28

This test is a pure block-by-block write throughput test, without any upper layer filesystem, into a bucket (subdirectory) that is completely empty.

What happens when you try a similar test as shown above using your machine?

**Comment by semhoun** [comment]
I use the same test than you and I foud why we don't have the same results, it's because of the blocksize of 1M and you 256M.
This is the new results:

_1.5.6 blockSize 256k:_ 
262144000 bytes (262 MB, 250 MiB) copied, 95.6557 s, 2.7 MB/s
0.01user 8.70system 1:35.65elapsed 9%CPU (0avgtext+0avgdata 2424maxresident)k
0inputs+0outputs (0major+166minor)pagefaults 0swaps

_1.6.3 blockSize 256k:_
262144000 bytes (262 MB, 250 MiB) copied, 41.5494 s, 6.3 MB/s
0.01user 8.48system 0:41.55elapsed 20%CPU (0avgtext+0avgdata 2284maxresident)k
0inputs+0outputs (0major+159minor)pagefaults 0swaps

_1.5.6 blockSize 1m:_
262144000 bytes (262 MB, 250 MiB) copied, 32.0314 s, 8.2 MB/s
0.01user 7.91system 0:32.03elapsed 24%CPU (0avgtext+0avgdata 2308maxresident)k
0inputs+0outputs (0major+162minor)pagefaults 0swaps

_1.6.3 blockSize 1m:_
262144000 bytes (262 MB, 250 MiB) copied, 61.4165 s, 4.3 MB/s
0.00user 9.56system 1:01.41elapsed 15%CPU (0avgtext+0avgdata 2284maxresident)k
0inputs+0outputs (0major+159minor)pagefaults 0swaps

**Comment by semhoun** [comment]
I continue my tests, if i add --directIO results completly change with 1.6.3 (the test is the same than previously)
blockSize 128k: 24 s, 10.7 MB/s
blockSize 256k: 34 s, 7.6 MB/s
blockSize 512k: 19 s, 13.0 MB/s
blockSize 1m: 14 s, 17.9 MB/s
blockSize 4m: 14 s, 17.8 MB/s
blockSize 8m: 19 s, 13.5 MB/s

**Comment by archiecobbs** [comment]
OK this helps.

First, realize that if the s3backer block size is `X`, and you read or write a block of size `Y != X`, then things will be slow because s3backer has to do multiple reads & writes to "patch" in the partial block(s).

That is also why `--directIO` will make a big difference, because without that flag the kernel is not buffering for you.

So all tests should be using `dd .. bs=X` where `X` is the s3backer block size to avoid "patching" effects...

**Comment by semhoun** [comment]
I continue my tests, and i that that network usage is also affected. With version 1.5.6 is 43MB/s and 1.6.3 4MB/s .

I will redo the tests blocksize with good value for dd and check the network usage.

I hope, I don't bother you with all my comments.

**Comment by archiecobbs** [comment]
> I hope, I don't bother you with all my comments.

Not at all. It just takes a while to narrow down to a single variable :)

**Comment by semhoun** [comment]
Some new tests only in 1.6.3 with and without DirectIO. I will try to do to sync with directio 800go of data.

**DD block same size / DirectIO:**
_128k:_
dd: 22.696 s, 11.8 MB/s
network: 6MB/s

_256k:_
dd: 36.0085 s, 7.5 MB/s
network: 11MB/s

_512k:_
dd: 21.6904 s, 12.4 MB/s
network: 16MB/s

_1m_:
dd: 15.5415 s, 17.3 MB/s
network: 22MB/s

_4m:_
dd: 14.8195 s, 18.1 MB/s
network: 23MB/s


**DD block same size / No DirectIO:**
_128k:_
dd: 68.2631 s, 3.9 MB/
network: 6MB/s

_256k:_
dd: 46.3428 s, 5.8 MB/s
network: 8MB/s

_512k:_
dd: 45.2558 s, 5.9 MB/s
network: 8MB/s

_1m:_
dd: 67.2015 s, 4.0 MB/s
network: 5MB/s

_4m:_
dd: 205.144 s, 1.3 MB/s
network: 3MB/s

**Comment by archiecobbs** [comment]
Interesting. When you don't use `--directIO` it probably disrupts the block size matching that you would otherwise get by using `dd`.

You also might try running in the foreground with `-f --debug` so you can see what reads & writes s3backer is actually doing.

**Comment by semhoun** [comment]
I try `--directIO` for 900Gb, but it don't work too many error during the copy with rclone (and it take more than 4 days).
I'll try with `-f --debug` but i've a lot of work this week.

**Comment by archiecobbs** [comment]
I'm pretty sure this is the same issue as #185, so I'm closing this issue as a duplicate.
