### ISSUE TITLE
BackBlaze B2 and other S3 compatibles

### ISSUE THREAD

**Issue by HaleTom** [archiecobbs/s3backer#159]
BackBlaze B2 exposes their storage via a S3 API.

How well does this work with that, or Wasabi, or anything else that's not S3?

I realise it would depend on the implementation, but I hope to have a googleable resource via this issue.

**Comment by HaleTom** [comment]
I just saw that #157 is hosting their filesystem on wasabi, and it's fscking just fine.

**Comment by archiecobbs** [comment]
In theory if it's S3 compatible, it should work. In practice people are doing this though I couldn't enumerate the specific alternatives in use today.

If you have problems, open a new issue with details and we can try to figure out what's wrong.
