### ISSUE TITLE
Little adjustment on endpoint URLs

### ISSUE THREAD

**Issue by acsfer** [archiecobbs/s3backer#167]
When using a `--region=eu-central-1` region, URL seems to translate (this is what logs output):
`https://<bucketname>.s3-eu-central-1.amazonaws.com/`

After the [official Amazon docs](https://docs.aws.amazon.com/general/latest/gr/s3.html), URL should be (please note the `.` instead of `-` after `s3`:
`https://<bucketname>.s3.eu-central-1.amazonaws.com/`

Also, using [dualstack endpoints](https://docs.aws.amazon.com/AmazonS3/latest/userguide/dual-stack-endpoints.html#dual-stack-endpoints-description) **as default** could help for IPv6 only hosts:
`https://<bucketname>.s3.dualstack.<region>.amazonaws.com/`

**Comment by archiecobbs** [comment]
Thanks. Should be fixed by 14429bb.

**Comment by archiecobbs** [comment]
For dualstack it looks like you should be able to just say e.g. `--region=dualstack.eu-central-1`.

**Comment by acsfer** [comment]
Fine for me (maybe document it).

**Comment by acsfer** [comment]
Will do.

**Comment by acsfer** [comment]
Doesn't work with `--baseURL=https://<bucketname>.s3.dualstack.eu-central-1.amazonaws.com/`

but works with `--baseURL=https://s3.dualstack.eu-central-1.amazonaws.com/`

**Comment by archiecobbs** [comment]
OK great, thanks for checking.
