### ISSUE TITLE
Internal block cache vs bcache

### ISSUE THREAD

**Issue by HaleTom** [archiecobbs/s3backer#169]
The README says:

> s3backer also includes its own internal block cache for increased performance, using asynchronous worker threads to take advantage of the parallelism inherent in the network.

[`bcache`](https://www.kernel.org/doc/Documentation/bcache.txt) is also a block cache, but implemented in the kernel.  Why not use this cache instead?

1. If there is no internal cache and a write is interrupted (eg power failure) before it reaches the S3 backing storage, is it lost?  If no, how is it stored for replay?

1. Is the internal write-back cache intended to be used at sizes of SSDs, eg 256GB+ like `bcache`?

1. Besides parallel async worker threads, are there any other advantages of using the internal cache over `bcache`?

1. Do you see any advantages if using `bcache` over the internal cache?

1. Do you see any advantages of using `bcache` in conjunction with the internal cache? (eg maybe a small internal cache just as a holding pen for the parallel async threads?)

**Comment by archiecobbs** [comment]
Hi @HaleTom,

I've never used bcache myself but I think you're probably right that it would be a better and more robust solution for the same problem. I will add a note to the man page.

A couple of small caveats:

1. s3backer can run on non-Linux systems (e.g. Mac OS) so bcache is not always an option, and
2. The s3backer block cache was written before I had ever heard of bcache, and so there is no implication that using bcache would be in any way insufficient.

> If there is no internal cache and a write is interrupted (eg power failure) before it reaches the S3 backing storage, is it lost? If no, how is it stored for replay?

Without any caching, writes are synchronous, so the kernel would not have gotten a successful result yet, so no the data should not be lost.

> Is the internal write-back cache intended to be used at sizes of SSDs, eg 256GB+ like bcache?

Should work I think...

> Besides parallel async worker threads, are there any other advantages of using the internal cache over bcache?

Not that I know of... though I've never used bcache and am not very familiar with it.

> Do you see any advantages if using bcache over the internal cache?

Definitely! Then questions and bug reports would go to someone else :)

> Do you see any advantages of using bcache in conjunction with the internal cache? (eg maybe a small internal cache just as a holding pen for the parallel async threads?)

Probably not, unless bcache is not capable of asynchronous write-back itself. But I think it is.

**Comment by HaleTom** [comment]
Thanks for the `man` page update!  I'll update this issue if/when I get some performance figures with `bcache`.
