### ISSUE TITLE
Unit sizes

### ISSUE THREAD

**Issue by HaleTom** [archiecobbs/s3backer#171]
Which units are the K, G, M, T specified in the man page?

SI (increases by 10^3) or IEC (increases by 2^10)?

Generally blocks are specified in KiB (IEC).

https://en.wikipedia.org/wiki/Binary_prefix

In the `--size` section, you seem to be missing P == 1024 or 1000 = G.

**Comment by archiecobbs** [comment]
Thanks - added clarification to man page in 3ddb333.
