### ISSUE TITLE
Confusing errors when not specifying bucket region

### ISSUE THREAD

**Issue by Nikratio** [archiecobbs/s3backer#174]
I've never used this bucket before, but:

```
> ./s3backer --blockSize=512K nikratio-test/s3backer ~/tmp/mnt  
s3backer: auto-detecting block size and total file size...
s3backer: error: auto-detection of filesystem size failed; please specify `--size'

./s3backer --blockSize=512K --size=50G nikratio-test/s3backer ~/tmp/mnt
s3backer: auto-detecting block size and total file size...
s3backer: auto-detection failed; using configured block size 512k and file size 50g
s3backer: http://s3.amazonaws.com/nikratio-test/s3backer/ appears to be already mounted (using mount token 0x00000001)
s3backer: reset mount token with `--reset-mounted-flag', or use `--force' to override
```

**Comment by Nikratio** [comment]
....or maybe the problem is something else?

```
./s3backer --blockSize=512K --size=50G --reset-mounted-flag nikratio-test/s3backer
s3backer: auto-detecting block size and total file size...
s3backer: auto-detection failed; using configured block size 512k and file size 50g
s3backer: resetting mount token for http://s3.amazonaws.com/nikratio-test/s3backer/
s3backer: error clearing s3 mount token: Input/output error
```

**Comment by Nikratio** [comment]
I think my guess is correct. The redirect is a result of the request being sent to the wrong S3 endpoint, due to s3backer not knowing which region the bucket is in.

With `--region` I'm having slightly more success - a different error:

```
./s3backer --blockSize=512K --size=50G --region eu-west-2 nikratio-test/s3backer ~/tmp/mnt
s3backer: auto-detecting block size and total file size...
s3backer: can't read data store meta-data: Operation not permitted
```

**Comment by archiecobbs** [comment]
What do you suggest?

**Comment by Nikratio** [comment]
Well, ideally s3backer would honor the redirect response and transparently adjust the endpoint. If that's too complicated, exiting with a "ERROR: No/wrong region specified" error would be helpful :-).

**Comment by archiecobbs** [comment]
> ideally s3backer would honor the redirect response and transparently adjust the endpoint.

Unfortunately, it doesn't look like Amazon tells us where to redirect to... i.e., there's no `Location:` header in the `301` response.

However, we can certainly output a warning message with a hint in this situation...

**Comment by archiecobbs** [comment]
Added warning in f76c7e8.

There is still the unresolved question of why you got `403 Forbidden`, which would be due to some different problem.

If that's still occurring, please open a new ticket.

**Comment by Nikratio** [comment]
Hmm. That's surprising. Are you sure it's not filtered away / not printed for some reason? The API docs (https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html, search for "PermanentRedirect") are pretty clear about that.

In any case, you should be able to get the correct endpoint from the XML content of the message body.
