### ISSUE TITLE
PerformanceConsiderations - there is no "Buffer Cache" anymore

### ISSUE THREAD

**Issue by Nikratio** [archiecobbs/s3backer#177]
https://github.com/archiecobbs/s3backer/wiki/Performance-Considerations is a bit out of date. Since kernel  2.4.10, there is no "buffer cache" anymore, there is only the page cache. 

For more details, see eg. https://www.oreilly.com/library/view/understanding-the-linux/0596005652/ch15s02.html

**Comment by archiecobbs** [comment]
Thanks- I added your note to the wiki page.
