### ISSUE TITLE
Drop features for dealing with eventually consistent servers?

### ISSUE THREAD

**Issue by Nikratio** [archiecobbs/s3backer#183]
Given that AWS S3 now offers immediate consistency for all requests (https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/), would it make sense to drop the s3backer code that deals exclusively with eventual consistency (md5 cache, minWriteDelay, etc)?

I don't expect performance gain, but it may make the code less complex.

**Comment by archiecobbs** [comment]
Wow! I had not heard this and that's great news.

I think we should keep the ec_protect layer around, because other S3-compatible services may not provide this new guarantee.

But changing the default behavior so that ec_protect is not used (i.e., `----md5CacheSize=0`) would make sense.

**Comment by archiecobbs** [comment]
Done in a757248.
