### ISSUE TITLE
block cache entry shrink policy not documented

### ISSUE THREAD

**Issue by Nikratio** [archiecobbs/s3backer#193]
I was wondering which (clean) blocks will be removed from the block cache if the block cache is full and a new entry needs to be inserted. It would be great if the manpage could explain what policy is being used. Is it the least recently used? Or the least frequently used? Or the least recently inserted one?

**Comment by archiecobbs** [comment]
Thanks, should be fixed in 4b1be32.

Least recently accessed blocks are evicted first.
