### ISSUE TITLE
block cache flush and synchronous umount (with fuse)

### ISSUE THREAD

**Issue by jeromerobert** [archiecobbs/s3backer#197]
I would like to be sure that all blocks have been flushed before powering off my computer. Currently when unmounting  the `umount` command return before the block cache is flushed. The s3backer process keeps running in the background until all blocks have been flushed. To know when the flush is finished I use `ps` or `pgrep` to see if the s3backer process is still alive or not. This is not nice.

As far as I understand this is a limitation of  fuse and not of s3backer. `umount` or `fusermount -u` do not wait for `fuse_operations.destroy` to finish before return.

Fortunnalty the `sync` command and `fuse_operations.fsync` are synchronous. `fuse_operations.fsync` currently does nothing in s3backer.

Would it be possible to implement `fuse_operations.fsync` so that the user could flush the block cache with `sync /mnt/s3b/file` ?

**Comment by archiecobbs** [comment]
Prototyped in 2506800. Let me know if it looks like it's working. Thanks.

**Comment by jeromerobert** [comment]
It works ! Thank you.

The `sync` of  Amazon Linux 2 is too old to support file argument so I do `python -c 'from os import *;fsync(open("/mnt/s3backer/file",O_WRONLY|O_NONBLOCK))'`.

**Comment by archiecobbs** [comment]
Great - thanks for the positive report.
