### ISSUE TITLE
too many time_wait socket when writing to a newly created disk

### ISSUE THREAD

**Issue by VVoidV** [archiecobbs/s3backer#199]
I got  some log below when I write to a newly created disk. But when I overwrite some file， everything is fine. 
```
Nov 22 11:33:26 ecm-b0d3 nbdkit[29425]: s3backer: operation failed: Couldn't connect to server (will retry)
Nov 22 11:33:56 ecm-b0d3 nbdkit[29425]: s3backer: operation failed: Couldn't connect to server (will retry)
Nov 22 11:34:28 ecm-b0d3 nbdkit[29425]: s3backer: operation failed: Couldn't connect to server (will retry)
Nov 22 11:35:01 ecm-b0d3 nbdkit[29425]: s3backer: operation failed: Couldn't connect to server (will retry)
```

I found it will use a lot of short link when writing to brand new block.  There will be 24000 time_wait tcp sockets.
I think we shoud reuse curl handle when we get 404 with GET request.

I also did some experiment, when I reuse curl handle  by this way, the problem goes away and the perf increase.
![image](https://user-images.githubusercontent.com/17823956/204689241-db573f21-f992-4c35-8743-52f0f76e3906.png)

I am not familiar to libcurl, can we reuse the handle on http server return some error status?

**Comment by archiecobbs** [comment]
Good idea - thanks. Should be fixed in 2c837c3.
