### ISSUE TITLE
Feature Request: DEBs and RPMs built by github actions when tagging a release

### ISSUE THREAD

**Issue by michael-conrad** [archiecobbs/s3backer#210]
I was looking to install the 2.x branch as a binary to use the NBD functionality, but I can't find where it has been built as part of a PPA or direct download.

I'm using Ubuntu and the upstream version seems a bit stale: 1.5.4-2build1

I see the option for github actions to build packages:

* DEB: https://github.com/jiro4989/build-deb-action
* RPM: https://github.com/jiro4989/build-rpm-action

**Comment by archiecobbs** [comment]
Thanks for the suggestions but - my apologies - I don't have the bandwidth to get into the packaging business. I'll have to leave that to others.

As a workaround, you could fork this project, add the github actions to the fork, and get notifications from this project so you'd know when to to merge in any updates as they occur.
