### ISSUE TITLE
Upgrade from 1.4.3

### ISSUE THREAD

**Issue by dflipse** [archiecobbs/s3backer#213]
Hi, I have been using a dated Ubuntu Bionic package release of s3backer for significant time. I decided it's time to upgrade. Unfortunately, I fail to mount my s3backer file system successfully. I tried several versions, as low as 1.6.3, all having the same problem. I use following instruction:

s3backer --force --blockSize=1m --size=128g --listBlocks --baseURL=https://gateway.storjshare.io/ --encrypt --passwordFile=secret --accessFile=key bucket mnt

Using 1.4.3 I get:

s3backer: auto-detecting block size and total file size...
s3backer: auto-detected block size=1m and total size=128g
s3backer: listing non-zero blocks................................done
s3backer: found 7598 non-zero blocks

Using latest version, I get:

s3backer: auto-detecting block size and total file size...
s3backer: auto-detected block size=1m and total size=128g
2023-10-13 21:00:01 INFO: established new mount token 0x0bd8b4c5

In both cases I get a mnt/file and mnt/stats, yet, only with 1.4.3 this is error-free, my btrfs gets detected with blkid and I can losetup/mount this without problems. With newer versions, I get errors and blkid does not detect a uuid and fs. Some kernel msg:

[ 3315.749277] BTRFS error (device loop0): devid 2 uuid 619a609d-e531-4720-b0e9-01b270f7087e is missing

It seems to me that listblocks is getting skipped over, with newer versions, even though I specify this. The command completes much faster (too fast).

Can you/someone advise how to proceed from here?

Thanks
Daniel

**Comment by archiecobbs** [comment]
What version is "latest version"?

FYI the reason list blocks is faster is because now it's done in the background.

Also, why are you using `--force`? It's dangerous because it means if you have s3backer running in two different places at the same time it won't be detected.

**Comment by dflipse** [comment]
Version 2.1.0; yet I tried 2.0.2 and 1.6.3 as well. I seem to be having problems mounting when list blocks hasn't completed. With these newer versions, is there a way to revert prevent backgrounding and revert to previous behaviour?

I have frequent crashes due out of memory problems which I am working to address. It's inconvenient to having to reset the mounted flag, every time. I am not running s3backer from other places at the moment

**Comment by archiecobbs** [comment]
> is there a way to revert prevent backgrounding and revert to previous behaviour?

No - but you could omit `--listBlocks` entirely and see if that helps.

> I am not running s3backer from other places at the moment

Good - just double checking.

To do more debugging we'll need some kind of reproducible test. Let me know if you find a way to do that.

**Comment by archiecobbs** [comment]
Closing old issue. Feel free to add more comments if new information becomes available.
