### ISSUE TITLE
Current state of NBD

### ISSUE THREAD

**Issue by aaruni96** [archiecobbs/s3backer#217]
I am interested in switching my s3backer from the FUSE mode to NBD mode.  While the current documentation still calls it "experimental", a couple days of testing in this mode didn't turn up any problems.

So my question is simply this: what is the current state of the NBD mode? Is there something holding it back from being marked "ready"? Are there some edge cases or "gotcha"s that I should be aware of, but haven't found yet ?

**Comment by archiecobbs** [comment]
It has actually gotten a good bit of testing since that documentation was written, so I'd say go for it.

I'll update the docs in the mean time.

Thanks.
