### ISSUE TITLE
Please update wiki for nbd

### ISSUE THREAD

**Issue by Lord-Dimwit-Flathead-the-Excessive** [archiecobbs/s3backer#218]
Please update/annotate configuration example for /usr/lib/systemd/system/s3backer-nbd.service:

ProtectKernelModules=true  # prevents main.c:try_to_load_nbd_module() from succeeding

nbd module must be loaded vi /etc/modules-load.d or manually

**Comment by archiecobbs** [comment]
Thanks for the report.

If you remove that line, does `try_to_load_nbd_module()` then succeed?

If so then we can just remove it from the example service file.

**Comment by archiecobbs** [comment]
I went ahead and removed it.

**Comment by Lord-Dimwit-Flathead-the-Excessive** [comment]
Yes it works great.

Gotta couple more for you ...
________________________________
