### ISSUE TITLE
s3backer-nbd does not create /run/s3backer-nbd directory

### ISSUE THREAD

**Issue by Lord-Dimwit-Flathead-the-Excessive** [archiecobbs/s3backer#219]
nbdkit may have created this parent directory when it created the socket at one time.  But it is not getting done now.

**Comment by archiecobbs** [comment]
That directory should be created during installation:
* `make install` - [here](https://github.com/archiecobbs/s3backer/blob/b3db14255350cb153c427c095e54682626511bdf/Makefile.am#L89-L91)
* RPM install - [here](https://build.opensuse.org/package/view_file/filesystems/s3backer/s3backer.spec?expand=1)

**Comment by Lord-Dimwit-Flathead-the-Excessive** [comment]
They don't survive a reboot on Debian 12.  They need to be created when the service starts.  I saw that you do a check for the socket still being around.  Just plop a mkdir in there.

**Comment by archiecobbs** [comment]
Thanks. Should be fixed in df6a136.
