### ISSUE TITLE
cannot using --blockSize and --encrypt at same time

### ISSUE THREAD

**Issue by guentir** [archiecobbs/s3backer#50]
Hi all,

when i use --blockSize=1M i get always 1M-sized files on s3.
but when i combine --blockSize=1M with --encrypt, i get random-sized files on s3.

what i am doing wrong?

**Comment by archiecobbs** [comment]
When encryption is enabled, compression is also (automatically) enabled for security purposes. Therefore, blocks will often be smaller than the configured block size as stored in S3. However, the decompressed block is always exactly the block size.

**Comment by guentir** [comment]
Oh, thanks for the information.
Great piece of software!
