### ISSUE TITLE
Hot cache entries

### ISSUE THREAD

**Issue by xmas79** [archiecobbs/s3backer#51]
I think there is space for another optimization in the local caching area. The most often accessed blocks should stay in local cache more time than other blocks. This would allow s3backer to not perform network IO on blocks such as superblocks or inode block maps on ext4, which means more performance since they don't need to be queried again and again during heavy writes periods. A simple statistics I think should be enough to track these blocks and lock them in the cache.

**Comment by archiecobbs** [comment]
Yes this is feasible. However, the design should be based on measurements from actual experiments of normal usage, and as simple as possible.

E.g., something as simple as the following: may be sufficient: associate a single bit with each block that indicates whether the block has been read (a) only once, or (b) more than once. Then absolutely prioritize (b) over (a) for retention in the cache. Kind of analogous to Java's generational garbage collection.

Would you be willing to code up a simple experiment to gather statistics? This would simply record a histogram of blocks vs. number of times read, i.e., build a mapping from # times read to number of blocks read that many times. We would then look for a sharp drop-off between consecutive numbers, e.g., between #blocks read 1 time and #blocks read 2 times, and target that point.

**Comment by xmas79** [comment]
I don't actually understand if you want to target the whole filesystem or only the blocks that are cached.

My idea was something like this:

1) We create a map big enough to contain N times the block cache number (4k blocks in cache --> N*4k blocks in this map). This is to allow to track blocks "just" evicted from cache, and we do this by looking at hash collisions: N=4 means 4 blocks mapped to the same hash key, eg a pool of 4 blocks for each hash bucket, and we can hit the same hash key up to 4 times with different block numbers and we still don't lose statistics. So, we will increment the counters by looking at the hash key to identify the block pool, and then the block number inside the pool. If we hit with a 5th block number we replace the block number with the lowest counter (eg the less used). I would use 1 byte per entry to keep things simple enough to experiment, but we could use only 4 bits per entry, which should probably be good enough and halve the memory requirements, or double the tracked blocks. Should be tuned...
2) We increment a counter in this block map each time a block is written out to S3. Since write implies a read (unless already cached or zeroed), I would look more at writes than reads. To be investigated...
3) Each time we need to replace an entry we decrease all the counters in the pool, which eventually will reach zero, actually freeing the hash slot.
4) We replace a block if the corresponding counter in the block pool is lower than any other counters in the same block pool.

**Comment by archiecobbs** [comment]
So you'd be keeping statistics on a per-bucket basis. Makes sense.

I still think it's worthwhile to try to better understand the real-world statistics before trying to design a solution. For example, it may be the case that 95% of blocks in the cache are only read once. If so, then the goal can be to simply to identify the other 5% and hold on to them more tightly... perhaps even more than one block per hash bucket if necessary, etc.

Of course to do this you'd have to come up with some "real-world" activity. E.g., Linux kernel compile? Web server? Hadoop?

Also, given an assumed statistical model of activity, you'd also want to show how whatever solution you came up with outperformed the existing LRU algorithm. If it's not sufficiently better, it may not be worth it.

Along these lines, there may simply be a small number of frequently accessed blocks that are colliding. In that case, allowing buckets to contain more than one block (while still imposing the overall maximum number of cached blocks) may be the only adjustment that's needed.

**Comment by xmas79** [comment]
I agree... The usage pattern is something that cannot be easily inferred. My idea was indeed partially targetting write operations (eg update disk free space in super blocks etc... during file copy), that causes a read when the block is not in the cache, stalling the IO. Could we use something like ARC to "infer" the access pattern?

**Comment by archiecobbs** [comment]
FYI - if a block is written frequently, then under the current logic it will stay in the cache because each time it's written it's LRU timestamp is reset (`block_cache.c`, line 1085).

**Comment by archiecobbs** [comment]
Regarding statistics, just some simple ones would probably suffice. Like a histograms showing #reads, time before re-read, etc.

**Comment by xmas79** [comment]
Yes, I saw the code, but it seems to me that the block won't survive a cache pollution (eg write a big file, where's the block that say "the available free disk space"? Will be often re-read and re-written), and a slowly writing pattern will evict that entry too, since it is "time" based and not "usage" based. no?

**Comment by archiecobbs** [comment]
You're right... if you read a bunch of blocks (more than your cache size) by e.g. scanning some large file, then that will quickly evict everything in the cache.

Sounds like some kind of two-level cache might work, where frequently read blocks are "promoted" to a smaller but stickier cache (this could even be a totally separate s3backer layer). That is, assuming this access pattern where you have occasional "blowouts" like described above that read a bunch of blocks only once.

**Comment by BuGlessRB** [comment]
The solution to this might be to simply have three LRU lists:
- One write (through) list, which can be configured but which should default to say 10% of the available disk cache space.
- One read list, which takes 80%.
- One hot list, which takes the remaining 10%.

The logic would then be:
- On block write, we check if the block is already on the read or hot list, if it is, save it at the top of the hot list instead (removing it from read, if needed).  If it is not, simply store it at the top of the write list.
- On block read, we check if the block is already on the write or hot list, if it is, save it at the top of the hot list instead (removing it from write, if needed).  It is not, simply fetch and store it at the top of the read list.

Blocks evicted from the hot list, are demoted to the write list if dirty, and demoted to the read list if clean.

If this sounds good, I'm willing to implement it.

**Comment by archiecobbs** [comment]
Side note: try out the `--blockCacheNumProtected` flag added in response to pr #119. For journaling filesystems where the journal is at the beginning (usually the case) this should help.

@BuGlessRB More generally, there are lots of possible ways to cache things and whether they are worthwhile depends a lot on the specific usage pattern. Experimentation is good and encouraged... though I can't promise ahead of time that any experiments will definitely be included in main codeline.

**Comment by archiecobbs** [comment]
Closing this (old) issue as the simplistic partial solution of `--blockCacheNumProtected` is a sufficient answer for now.
