### ISSUE TITLE
Licensing conflict

### ISSUE THREAD

**Issue by lhw** [archiecobbs/s3backer#53]
I'm currently thinking about getting s3backer into debian but it currently has a licensing conflict between GPL and the OpenSSL license. As these licenses are incompatible with each other.
There are two possible ways to resolve this conflict.
 * Replace OpenSSL with GnuTLS
 * Add a license exemption for OpenSSL to the source code.

For the later option there are already some prepared lines which can be easily added to the source code: https://people.gnome.org/~markmc/openssl-and-the-gpl.html and https://lists.debian.org/debian-legal/2004/05/msg00595.html

**Comment by archiecobbs** [comment]
Fixed by 481449a.

**Comment by lhw** [comment]
Thanks for your help. Really appreciate it. Didn't expect to get this all done today. 
Also, could you tag a new minor version for the changes? That would keep the version number smaller as it would be 1.4.1+git20150901 otherwise.

**Comment by archiecobbs** [comment]
Done.
