### ISSUE TITLE
Devices created with version 1.3.7 not accessible with current (1.4.2)

### ISSUE THREAD

**Issue by jmcorgan** [archiecobbs/s3backer#58]
Per title, I have a series of S3-backed devices using the 1.3.7 version of the software originally published at Google, which are working fine.

Attempting to mount them using the current master results in Amazon returning 'bad request' for every http attempt.

Not sure if this is a known issue or their was a format change or whatever; please let me know if you'd like further information to help debug.

**Comment by archiecobbs** [comment]
Hmm, not sure what it is.

Try these flags.... `--authVersion=aws2`, `--ssl`, and/or `--vhost`...

**Comment by jmcorgan** [comment]
Will do, thanks.

**Comment by jmcorgan** [comment]
So, using --authVersion=aws2 fixes the problem.  I don't understand enough about the S3 API to know why, or if this indicates some other issue.

**Comment by archiecobbs** [comment]
I think version 4 auth might not yet be supported in all regions or something. Which data center are you connecting to?

**Comment by jmcorgan** [comment]
us-west-1

**Comment by archiecobbs** [comment]
Hmm... 

You added *only* `--authVersion=aws2` but *not* `--ssl` or `--vhost` and it worked?

What happens when you try adding *only* `--ssl`?

**Comment by jmcorgan** [comment]
Yes, I only added --authversion=aws2 and not --ssl, to get it to work.

I just confirmed that adding instead --ssl, and not adding the authVersion option, fails with the same failure mode as originally.

With my immediate issue solved, feel free to close this issue, but if you think there still might be a problem indicated by the above, please let me know.

**Comment by archiecobbs** [comment]
Thanks. I'll leave this issue open for further investigation when time permits.

**Comment by archiecobbs** [comment]
Closing issue, problem resolved & not worth further investigation.
