### ISSUE TITLE
When data from the memory to the local cache, the speed is very slow, about 20M/s

### ISSUE THREAD

**Issue by Roay** [archiecobbs/s3backer#63]
Such as the title, Why?

**Comment by archiecobbs** [comment]
If I understand you correctly, you're saying that when you write new data and that data is cached, then the writing is slow.

Are you sure the slowness is not due to write-back of the cached data to S3?

**Comment by Roay** [comment]
Yes, the memory is written to the local cache, rather than the cached data written to the S3.For example, the block_size is 2M, the file system format for the XFS, when I write a large data, the cache file gradually become larger, the speed is 20M / s or so.

When I add print in the source code and found that each time you send a request to write data size is 4k. Since the block_size is 2M, so each block has requested 512 times before finish. This is the reason to cause performance degradation?

**Comment by archiecobbs** [comment]
Yes, most likely. A big mismatch like that between the filesystem block size and the s3backer block size, combined with a relatively short write back timeout, can result in a lot of back-and-forth.

You could try configuring the cache for a longer write-back timeout (`--blockCacheWriteDelay`), and/or make the XFS block size larger and/or the s3backer block size smaller.

**Comment by Roay** [comment]
All of my data are larger blocks, so s3backer's block a bit larger, I try to make the XFS block size larger, but I failed to mount the file. Because x86 linux machines kernel page size is 4k, file system block size can not be greater than page size.

**Comment by Roay** [comment]
A plurality of pieces(4k or smaller) written request may be combined into one large request written(2M or larger) to the cache ? 
If so, how can I do?

**Comment by archiecobbs** [comment]
Yes that will happen automatically if you increase `--blockCacheWriteDelay`, because the writes to S3 will be deferred, allowing s3backer to aggregate them.

**Comment by Roay** [comment]
This operation is performed in which layer, block cache layer or ec_protect layer or http_io layer?

**Comment by Roay** [comment]
How to improve the speed of writing data to the cache, rather than the speed of writing S3?

**Comment by archiecobbs** [comment]
I don't think the speed of writing to the cache is the problem unless you have really slow disks. That's just a simple disk write. The speed of network communication is much slower and typically dominates the equation.

In any case, you could add some debugging/profiling code if you wanted to that would reveal where time is being spent.

**Comment by Roay** [comment]
@archiecobbs ,  Well, thanks a lot.

**Comment by shakamd** [comment]
Going to bump this to hopefully get some input as I'm facing the same issue.

Depending on the configured s3backer block size, the amount of time it takes for fuse to write just to the block cache can vary significantly (for example, at 128K vs 8MB). You can configure the write-back timeout and the cache size to a significantly high value to remove the effects of slow backing storage while you test.

Intuitively, this makes sense. With a smaller block size, writes on the upper filesystem will repeatedly trigger reads on consecutive blocks to slurp them into the cache before they can be written to. However, I'm confused as to what's making the chain _so slow_. Even with a purely memory backed cache and blocks that just return zeroes, small blocks significantly hamper the speed at which data is written into the cache. I haven't been able to identify any particular piece of hot code that's responsible for the slowness, gprof merely indicates block_cache_write_block_part/block_cache_read_block_part.

Any ideas?

**Comment by archiecobbs** [comment]
FYI, in 2819cbe I added the `--test-discard` flag which should help to isolate the FUSE/s3backer overhead.

**Comment by shakamd** [comment]
Ahh, I had been using the --test flag this whole time, and didn't realize it was performing random delays by default (so smaller blocks = more delays). Throughput looks much better now. Thank you for refactoring that into its own flag!

**Comment by archiecobbs** [comment]
No prob, glad it's making more sense now.
