### ISSUE TITLE
Fails to build with openssl 1.1.0

### ISSUE THREAD

**Issue by lhw** [archiecobbs/s3backer#64]
Debian is currently testing OpenSSL 1.1.0 builds for the next version. s3backer fails to build with OpenSSL 1.1.0 due to API changes. Here is the debian build log: 
https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/s3backer_1.4.2-1_amd64-20160529-1533

And an abbreviated version with just the make: https://gist.github.com/lhw/2485f5659690ca5450e0b9805337fc0c

**Comment by archiecobbs** [comment]
Thanks for the heads-up. Patches welcome.

**Comment by bengoodwyn** [comment]
I am working on a patch

**Comment by bengoodwyn** [comment]
06ab702683561eef68613f052fde6d72d5f4916d compiles on a new and an old OpenSSL but hasn't been tested yet

**Comment by lhw** [comment]
That was quick. If the patch is merged could you tag a new release. I would then update the debian package asap.

**Comment by bengoodwyn** [comment]
v4 auth works with that patch, but v2 auth does not. I am looking into the issue.

**Comment by bengoodwyn** [comment]
Resolved an issue with the first commit. ea53694777386b3fa8e1579cb3ead620586a9e2c has been tested with v2 and v4 auth to S3 on Amazon AWS.

**Comment by lhw** [comment]
Could you tag a new minor release for the merged version? Makes the version management in debian a bit easier.

**Comment by archiecobbs** [comment]
Sure, version 1.4.3 released.

**Comment by lhw** [comment]
Uploaded it to debian testing. Oh and I noticed that _BSD_SOURCE is deprecated and being replaced by _DEFAULT_SOURCE for newer compilers.
But its not really an important change for now.

July 25 2016 9:03 PM, "Archie L. Cobbs"  wrote:
	Sure, version 1.4.3 released.
