### ISSUE TITLE
Support ACD

### ISSUE THREAD

**Issue by xelra** [archiecobbs/s3backer#67]
Is it possible, with minimal effort, to support also Amazon Cloud Drive? Maybe the API is the same.

**Comment by archiecobbs** [comment]
I don't think so. Amazon Cloud Drive is a much higher level service AFAICT.

**Comment by gordan-bobic** [comment]
The ACD API appears to be different, but logically it doesn't seem to be particularly dissimilar to S3. From the Amazon documentation:

S3 example:

PUT /ObjectName HTTP/1.1
Host: BucketName.s3.amazonaws.com
Date: date
Authorization: authorization string (see Authenticating Requests (AWS Signature Version
		4))

ACD example:

POST /cdproxy/nodes?localId=testPhoto
HTTP/1.1
Host: content-na.drive.amazonaws.com
Authorization: Bearer
Atza|IQEBLjAsAhReYeezFcFdYzqrFOJGv3EG
 
----WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="metadata"
 
{"name":"fooo.jpg","kind":"FILE"}
----WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="content";
filename="db5df4870e4e4b6cbf42727fd434701a.jpg"
Content-Type: image/jpeg
 
----WebKitFormBoundaryE19zNvXGzXaLvS5C

So the API layer would need to be replaced to use ACD, but the rest of the code would probably be reusable.

**Comment by xelra** [comment]
Yeah, I really love the idea of s3backer. Unfortunately S3 is not a very cheap storage. If it could be extended to Backblaze B2 and ACD that would awesome.

Reading this sentence 
> Only three HTTP operations are used: GET, PUT, and DELETE.

in the README, I thought that it might not be such a big undertaking to support other backends.

**Comment by gordan-bobic** [comment]
Also perhaps worth mentioning that if it is a matter of time/funding to support additional back-ends, I would certainly be willing to chip in a reasonable donation for ACD and Hubic support. It is plausible enough others would to make it viable.

**Comment by archiecobbs** [comment]
Just FYI from my end, I don't have time to work on this (even if I were being paid). However I'm happy to entertain patches (if they are reasonable) if you can find someone else to work on it.
