### ISSUE TITLE
--listBlocks incompatible with 'complex' --prefix argument

### ISSUE THREAD

**Issue by nielsenb-jf** [archiecobbs/s3backer#69]
When the prefix argument contains a folder separator (the forward slash character), including the `--listBlocks` option will result in a "s3backer: can't list blocks: Operation not permitted" error:

```
s3backer --size=16M --listBlocks --prefix=test/ s3b.mnt
s3backer: auto-detecting block size and total file size...
s3backer: auto-detection failed; using default block size 4k and file size 16m
s3backer: MD5 cache size (10000) is greater that the total number of blocks (4096); automatically reducing
s3backer: listing non-zero blocks...s3backer: can't list blocks: Operation not permitted
```

Omitting the `--listBlocks` options results in the expected, correct, behavior:

```
s3backer --size=16M --prefix=test/tset/ backer-prefix-test s3b.mnt
s3backer: auto-detecting block size and total file size...
s3backer: auto-detection failed; using default block size 4k and file size 16m
s3backer: MD5 cache size (10000) is greater that the total number of blocks (4096); automatically reducing
```

A 'simple' prefix argument does not produce the issue:

```
s3backer --size=16M --listBlocks --prefix=test backer-prefix-test s3b.mnt
s3backer: auto-detecting block size and total file size...
s3backer: auto-detection failed; using default block size 4k and file size 16m
s3backer: MD5 cache size (10000) is greater that the total number of blocks (4096); automatically reducing
s3backer: listing non-zero blocks...done
s3backer: found 0 non-zero blocks
```

Running in test mode does not produce the issue. This is using s3backer version 1.4.3

**Comment by archiecobbs** [comment]
Not sure what the problem is. Might be a permissions issue. Adding flags `-f --debug --http-debug` will show more info, including the Amazon HTTP response.

**Comment by nielsenb-jf** [comment]
It looks like the forward slashes aren't being URL escaped in the query portion of the GET request for listing non-zero blocks:

```
s3backer --size=16M --listBlocks --prefix=test/ -f --debug --http-debug backer-prefix-test s3b.mnt
s3backer: auto-detecting block size and total file size...
2016-11-16 09:23:32 DEBUG: HEAD http://s3.amazonaws.com/backer-prefix-test/test/00000000
2016-11-16 09:23:33 DEBUG: rec'd 404 response: HEAD http://s3.amazonaws.com/backer-prefix-test/test/00000000
s3backer: auto-detection failed; using default block size 4k and file size 16m
2016-11-16 09:23:33 DEBUG: HEAD http://s3.amazonaws.com/backer-prefix-test/test/s3backer-mounted
2016-11-16 09:23:33 DEBUG: rec'd 404 response: HEAD http://s3.amazonaws.com/backer-prefix-test/test/s3backer-mounted
s3backer: MD5 cache size (10000) is greater that the total number of blocks (4096); automatically reducing
s3backer: listing non-zero blocks...2016-11-16 09:23:33 DEBUG: GET http://s3.amazonaws.com/backer-prefix-test?max-keys=256&prefix=test/
2016-11-16 09:23:33 ERROR: rec'd 403 response: GET http://s3.amazonaws.com/backer-prefix-test?max-keys=256&prefix=test/
s3backer: can't list blocks: Operation not permitted
```

I'd expect the value of the prefix query parameter to be `test%2f`

**Comment by archiecobbs** [comment]
According to [this](https://www.talisman.org/~erlkonig/misc/lunatech%5Ewhat-every-webdev-must-know-about-url-encoding/):

> "/" is allowed unescaped anywhere within a query part

Also just curious, what happens if you say `--prefix=test%2f` ?

**Comment by nielsenb-jf** [comment]
Fails earlier with `--prefix=test%2f``:

```
s3backer --size=16M --listBlocks --prefix=test%2f -f --debug --http-debug backer-prefix-test s3b.mnt
s3backer: auto-detecting block size and total file size...
2016-11-16 10:30:37 DEBUG: HEAD http://s3.amazonaws.com/backer-prefix-test/test%2f00000000
2016-11-16 10:30:37 ERROR: rec'd 403 response: HEAD http://s3.amazonaws.com/backer-prefix-test/test%2f00000000
s3backer: can't read data store meta-data: Operation not permitted
```

**Comment by archiecobbs** [comment]
I have no idea what the problem is... I don't see where we are doing anything wrong. If you can find some documentation that says otherwise I'd be interested to see it.

**Comment by nielsenb-jf** [comment]
For what it's worth, the request succeeds using curl with and without the forward slash escaped.

**Comment by archiecobbs** [comment]
Ah... it's possible there is a bug in how we are doing the authentication hash, which includes the URL.

Your test with curl is not doing any authentication, correct? That is, the bucket is world readable.

Can you also try the original test with `--authVersion=aws2` ?

**Comment by nielsenb-jf** [comment]
Correct, the curl test was with the bucket world readable; no authentication.

The original test with `--authVersion=aws2` works correctly.

**Comment by archiecobbs** [comment]
Please try 1bc73e3.

**Comment by nielsenb-jf** [comment]
1bc73e3 fixes the issue.

**Comment by archiecobbs** [comment]
Great, thanks for verifying the fix.
