### ISSUE TITLE
Block size and IV length for ciphers

### ISSUE THREAD

**Issue by TomCrypto** [archiecobbs/s3backer#70]
Is there a particular reason why s3backer enforces that the block size must equal the IV length for the cipher used for encryption? I took a look through the code and can't see anything that would obviously require that.

The issue is that this requirement essentially forces the user to use CBC mode, as in openssl all streaming modes of operation (CTR, OFB, CFB, etc) have a block size of 1 byte by construction, but a longer IV (e.g. 16 bytes).

I might fix it myself later on but it will have to wait as I have too much going on at the moment.

**Comment by archiecobbs** [comment]
Good point. Fixed in 51370b9f.

**Comment by TomCrypto** [comment]
Awesome, thanks for the prompt response!

**Comment by archiecobbs** [comment]
No problem... I'd appreciate your adding a comment if/when you've had a chance to test out some of the stream encryption modes to let me know that they work OK.
