### ISSUE TITLE
Encryption failed, why?

### ISSUE THREAD

**Issue by Roay** [archiecobbs/s3backer#71]
I use the 1.4.3 version, the order is as follows:
s3backer --accessId=XXXX --accessKey=XXXXXXX --size=20G --blockCacheFile=/root/cache1 --authVersion=aws2 --baseURL=https://XXXX/ --blockCacheSize=1024 --prefix=01 --blockSize=1M --force --debug -f   --encrypt --password="12de" --compress=9  --ssl test /root/fileDir/

but report the error：
2017-01-12 16:56:01 ERROR: block 00000000 is encrypted, but no signature was found

why?

**Comment by archiecobbs** [comment]
Does `https://XXXX/' mean you're connecting to something other than Amazon?

**Comment by Roay** [comment]
Yes, based on the S3 interface. What is the problem?

**Comment by archiecobbs** [comment]
Can you run the same test against Amazon S3? This will help narrow down the problem.

**Comment by Roay** [comment]
Sorry, I do not have an Amazon account

**Comment by Roay** [comment]
Does http head information stored in the S3 object?

**Comment by ethus3h** [comment]
This looks similar to me to the feature request #68, which was kindly implemented in a not-yet-released version. @Roay, perhaps you would find the not-yet-released version with that feature to fix this issue?

**Comment by archiecobbs** [comment]
Ah yes, thank you @ethus3h. The best bugs are the ones that have already been fixed :)
