### ISSUE TITLE
./autogen.sh required before ./configure ?

### ISSUE THREAD

**Issue by ahmgithubahm** [archiecobbs/s3backer#74]
This may be something I did wrong, but when following the wiki section covering building from source ( 
https://github.com/archiecobbs/s3backer/wiki/BuildAndInstall#building-and-installing-from-source ), I couldn't run ./configure because it doesn't exist!  I guessed at running ./autogen.sh first, and then was able to continue fine.

If it matters, this was on CentOS 6 x86_64, with a cloned repo.

Just a change required to the Wiki page, and maybe the INSTALL file as well ?

thanks

**Comment by archiecobbs** [comment]
I updated the wiki page. Those instructions are for building from the unpacked distribution source tarball. See new wiki update for building from the github source.
