### ISSUE TITLE
Question: has anyone tried using f2fs with s2backer?

### ISSUE THREAD

**Issue by ThePythonicCow** [archiecobbs/s3backer#75]
Instead of formatting the file system inside s3backer using ext4, reiserfs, btrfs, ... has anyone tried using f2fs, the flash friendly file system.  It seems to me, at first glance, that this combination might work quite well, as the effort by f2fs to adapt to the native block size of a flash drive (which might be a megabyte or two), and to minimize the number of such blocks written, might work well when it's an "S3" based drive, rather than a "Flash" based drive.

**Comment by archiecobbs** [comment]
I haven't heard of anyone doing that, though it sounds like an interesting idea.

You might post this question on the s3backer group: https://groups.google.com/forum/#!forum/s3backer-devel
