### ISSUE TITLE
Prefix block names with hash string to evenly distribute them

### ISSUE THREAD

**Issue by archiecobbs** [archiecobbs/s3backer#80]
See [this thread](https://groups.google.com/forum/#!topic/s3backer-devel/BoltlgaiLJM).

Create new option to add a standard-length prefix which is computed using some deterministic hash function of the block number.

Then you'd get blocks with names looking like this:

```
  DD54012685DF-00000000
  A92813B38727-00000001
  F125D1ABE971-00000002
  4C382BB43B4F-00000003
```

This would avoid [this problem](https://www.google.com/url?q=https%3A%2F%2Fdocs.aws.amazon.com%2FAmazonS3%2Flatest%2Fdev%2Frequest-rate-perf-considerations.html&sa=D&sntz=1&usg=AFQjCNFH8_H0ni0GtBPPb7e8NjQJtyisvQ).

**Comment by xmas79** [comment]
That seems related to what I implemented in my PR with the bit reversal stuff.

**Comment by archiecobbs** [comment]
Added `--blockHashPrefix` flag in 5fa4b6e.
