### ISSUE TITLE
Concepts about S3backer

### ISSUE THREAD

**Issue by obenziane21** [archiecobbs/s3backer#83]
I have a bucket mounted successfully but i don't understand the concept here.

I have uploaded testfile1, testfile2, etc.. into my bucket and they just look like 000000, 0000380 as show in the screenshot. But how can i view what's in there and pick a file and uses it from the application ?

Here is my mount:

`https://myprivatebucket.s3.amazonaws.com/ on /s3-mnt type fuse.s3backer (rw,nosuid,nodev,allow_other,default_permissions)
/s3-mnt/file on /s3-data type ext4 (rw)`

Setup:

1. `s3backer --blockSize=1024k --size=2g --listBlocks --vhost --ssl --timeout=250 --blockCacheThreads=3 --maxUploadSpeed=35k myprivatebucket /s3-mnt`

2. `mkfs.ext4 /s3-mnt/file`

3. `mount -t ext4 -o loop /s3-mnt/file /s3-data`

<img width="1250" alt="screen shot 2017-08-18 at 11 45 49 am" src="https://user-images.githubusercontent.com/29074361/29472989-d4825b4e-840a-11e7-8dd3-ca1a6c3d96b6.png">

**Comment by archiecobbs** [comment]
Your files will only be accessible from the loopback mount `/s3-data`.

The "files" that you seen in the AWS console are just "disk blocks" written by the filesystem - in your case, ext4.

s3backer doesn't know anything about files. That's the filesystem's job.
