### ISSUE TITLE
Does s3baker support swift v1.0 certification?

### ISSUE THREAD

**Issue by RayOsLei** [archiecobbs/s3backer#84]
Attached command as following :

```shell
# s3backer --blockSize=4K --listBlocks --size=1T jjj /mnt/win_duck/ --accessId="test:tester" --accessKey="5f055c853d249b2d75964a66a68f9e92f741c095965f8ee1d5057f90b924ecc6cb3b56c12f12ccb829ac1ffe5be587c048b1bc5d25b6818aa4d11f80060d7c9a" --authVersion="aws2" --baseURL="http://127.0.0.1:8080/" --debug --debug-http
```

But it reported such a mistake：

s3backer: auto-detecting block size and total file size...

* About to connect() to 127.0.0.1 port 8080 (#0)
* Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> HEAD /jjj/00000000 HTTP/1.1
> User-Agent: s3backer/1.4.4/1.4.3-11-g37e55cd
> Host: 127.0.0.1:8080
> Accept: /
> Date: Mon, 09 Oct 2017 13:33:05 GMT
> Authorization: AWS test:tester:GQFvMXFP0eeYN5vW/qFNgHUEzLQ=

* The requested URL returned error: 403 Forbidden

* Closing connection 0
  s3backer: can't read data store meta-data: Operation not permitted

  my ~/.s3cfg:

  ```
  [default]

  access_key = test:tester

  host_base = 127.0.0.1:8080

  host_bucket = 127.0.0.1:8080

  use_https = False

  secret_key = 5f055c853d249b2d75964a66a68f9e92f741c095965f8ee1d5057f90b924ecc6cb3b56c12f12ccb829ac1ffe5be587c048b1bc5d25b6818aa4d11f80060d7c9a
  signature_v2 = True
  ```

  and s3cmd ls works:

  ```shell
  # s3cmd ls
  2009-02-03 16:45  s3://con1

  2009-02-03 16:45  s3://ggg

  2009-02-03 16:45  s3://oss

  2009-02-03 16:45  s3://p2p

  2009-02-03 16:45  s3://ppp

  2009-02-03 16:45  s3://s3bucket
  ```

I'm sure my username and password are correct，Is not what parameters are less？

**Comment by archiecobbs** [comment]
The file `~/.s3cfg` is not related to `s3backer`. Are you perhaps confusing `s3backer` with some other program?

**Comment by RayOsLei** [comment]
I cite the purpose of this example is to prove my username and password are correct, I can use s3cmd certification, but s3backer certification can not pass, I would like to ask, where my configuration wrong?
@archiecobbs

**Comment by archiecobbs** [comment]
I don't see anything wrong with your command line.

Are you actually connecting to Amazon somehow (indirectly) via `127.0.0.1`, or are you connecting to some other S3-type service? It looks like the latter, in which case you'll need to investigate that service as to why it's returning `403 Prohibited`.
