### ISSUE TITLE
support _netdev option

### ISSUE THREAD

**Issue by sauyon** [archiecobbs/s3backer#85]
A _netdev option can be passed to mount options to make systemd mount it later, meaning that it can be automounted. However, s3backer doesn't support this option, meaning that the mount will fail. Can this be fixed?

**Comment by archiecobbs** [comment]
The `_netdev` flag is not passed to the filesystem, but is a hack to alert whatever process parses `/etc/fstab` to delay the mount until the network is available ([more info](https://unix.stackexchange.com/questions/169697/how-does-netdev-mount-option-in-etc-fstab-work)). So it has nothing directly to do with `s3backer`.

In fact I use this flag myself and it works fine.  Note you need to put it on *both* mounts, the `s3backer` mount and the loopback mount.

Here's an excerpt from my `/etc/fstab`:

```

# s3disk
s3backer#example     /home/archie/mnt/s3b    fuse            force,size=1t,blockSize=256k,encrypt,compress=9,passwordFile=/home/archie/.s3backer_cryptkey,accessFile=/home/archie/.s3backer_passwd,prefix=example-,blockCacheSize=4000,blockCacheFile=/home/archie/mnt/cachefile,blockCacheWriteDelay=15000,blockCacheThreads=4,timeout=90,_netdev 0 0
/home/archie/mnt/s3b/file /home/archie/mnt/rebound ext4     loop,discard,noatime,nodiratime,_netdev,x-systemd.requires=home-archie-mnt-s3b.mount 0 0

```

Note the `_netdev` and `x-systemd.requires=` flags.

**Comment by sauyon** [comment]
Ah, perhaps this is a NixOS problem then. I apologize.
