### ISSUE TITLE
Update build/install instructions for FreeBSD

### ISSUE THREAD

**Issue by staktrace** [archiecobbs/s3backer#92]
s3backer compiles and runs (at least the demo) on FreeBSD pretty easily. I was able to do it on an EC2 instance with a clean FreeBSD 11.2-RELEASE image. Here are instructions if you'd like to update the wiki.

## Basic setup ##
This part is just to get a development environment on top of the EC2 base image. See the first few sections of [my blog post](https://staktrace.com/spout/entry.php?id=840) for how to get the EC2 image in the first place. Install the basic development stuff and dependencies, as root:
`pkg install -y git bash gcc automake autoconf`
Ensure the ec2-user account is using bash:
`chsh -s /usr/local/bin/bash ec2-user`

You additionally need these for s3backer:
`pkg install -y pkgconf fusefs-libs`

## Build s3backer ##
As the ec2-user, clone the repo (including PR #91) and then run the usual build steps:
```
./autogen.sh
./configure
make
```

Presumably you can do `make install` too at this point, but I was satisfied with the s3backer binary being built.

## Demo ##
As root:
```
kldload fuse ext2fs  # need fuse obviously, ext2fs for mounting the linux demo file
mkdir s3b.mnt demo.mnt
PATH/TO/s3backer --readOnly s3backer-demo s3b.mnt
mdconfig -a -t vnode -f s3b.mnt/file   # make a memory device from the file, this will output md0 or similar
mount -t ext2fs /dev/md0 demo.mnt   # replace md0 with output of last command
cat demo.mnt/README
```

Note that I run all these steps as root because I get permission errors when trying to run s3backer as a regular user. I get these errors on macOS as well so presumably it's unrelated.

**Comment by archiecobbs** [comment]
Thanks.

Have you considered trying to get `s3backer` added to FreeBSD ports?

**Comment by staktrace** [comment]
I'm not familiar with the process for doing that, but yeah, I would like to see that happen. I'll work on it as time permits.

**Comment by staktrace** [comment]
Ok, I think I have the port scripts set up to add `s3backer` to the ports collection. However, could you make a new 1.5.1 release tarball that includes #91? Otherwise I will need to include that change as a separate patch file in the port. If there is a tarball available on the github release page I can use that directly. Once that is done I'll try to submit the port.

**Comment by archiecobbs** [comment]
I just released 1.5.0 a month ago, so a new release is not really warranted. Just include the patch in the port for now. Thanks for creating the port.

**Comment by archiecobbs** [comment]
Wait a minute, that patch should not even be necessary. The `autogen.sh` script is only used for developers. The [normal distribution](https://s3.amazonaws.com/archie-public/s3backer/s3backer-1.5.0.tar.gz) doesn't even include that script.

**Comment by staktrace** [comment]
Oh.. I didn't realize you had separate distributions for developers and non-developers. What's the point? i.e. developers can use the git repo directly, what is the purpose of the tarball that is in the github releases section?

**Comment by archiecobbs** [comment]
Github does that automatically. It's just a tarball of the source tree.

The official "distribution" is different - it's a portable self-configuring (`./configure`) build of the software. See `autoconf` for more info; that's the tool that builds the distribution tarball from the raw source.

**Comment by staktrace** [comment]
I filed https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229998 to get the port added.

**Comment by staktrace** [comment]
The port has been added; presumably it will get into the binary package system soon.

**Comment by archiecobbs** [comment]
Great, thanks.
