### ISSUE TITLE
blockCacheSize Ignored with non-default blockSize

### ISSUE THREAD

**Issue by gordan-bobic** [archiecobbs/s3backer#94]
It looks like bockCacheSize is ignored with blockSiize != 4096.
I just set --blockSize=1M --blockCacheSize=[4096|16384], and in both cases it looks like it only buffers up about 500MB (size of the process, and the point at which the writes stall under a heavy load).

**Comment by archiecobbs** [comment]
- How big is your filesystem? I.e., how many total blocks?
- Have you enabled compression?

**Comment by gordan-bobic** [comment]
s3backer is started with:
compress=1
blockSize=1M
size=700G
blockCacheWriteDelay=10000
blockCacheThreads=200

**Comment by archiecobbs** [comment]
OK time to debug. Run with `--blockCacheSize=16384`, then get it fully saturated, then run `cat mnt/stats` and copy the output here.
