### ISSUE TITLE
configure: error: required library libfuse missing on Mac OS

### ISSUE THREAD

**Issue by nikitadm** [archiecobbs/s3backer#95]
Mac OS doesn't support libfuse and following command from <a href ="https://github.com/archiecobbs/s3backer/wiki/Build-and-Install">Build and Install</a> requires libfuse,

PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure

Can you provide detailed steps for s3backer installation on Mac OS?

**Comment by nikitadm** [comment]
Installation of s3backer via brew is supported.

'brew install s3-backer'

@archiecobbs could you please update the documentation?

**Comment by archiecobbs** [comment]
@nikitadm, wiki updated, thanks for the reminder.
