### ISSUE TITLE
s3backer: can't read data store meta-data: Input/output error

### ISSUE THREAD

**Issue by nikitadm** [archiecobbs/s3backer#96]
Hi @archiecobbs,
I am using non-aws s3 provider

I have setup my credentials in .s3backer-password file in following format
<accessKey>:<secretKey>

Following is the command I am using to mount my bucket

_**s3backer --accessFile=.s3backer-password --baseURL=http://non-aws-provider.com:8080/MYBUCKET  mount/point -d --debug --debug-http -f --region="us-east-1" --vhost --authVersion=aws2**_

But I get following error, 
s3backer: auto-detecting block size and total file size...
2018-09-05 10:51:07 DEBUG: HEAD http://MYBUCKET.non-aws-provider.com:8080/00000000
*   Trying 00.00.00.55...
* TCP_NODELAY set
* Connected to MYBUCKET.non-aws-provider.com (00.00.00.55) port 8080 (#0)
> HEAD /00000000 HTTP/1.1
Host: MYBUCKET.non-aws-provider.com:8080
User-Agent: s3backer/1.5.0/1.5.0
Accept: */*
x-amz-date: 20180905T145107Z
x-amz-content-sha256: efjnfjfgyfyggdhdhejifnjnweufhueiwiwhuehuf4y4hg5ui43
Authorization: AWS4-HMAC-SHA256 Credential=<accessKey>/20180905/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=<signature>

* Empty reply from server
* Connection #0 to host MYBUCKET.non-aws-provider.com left intact
2018-09-05 10:51:37 ERROR: operation failed: Server returned nothing (no headers, no data) (final attempt)
2018-09-05 10:51:37 ERROR: giving up on: HEAD http://MYBUCKET.non-aws-provider.com:8080/00000000
s3backer: can't read data store meta-data: Input/output error

**Comment by nikitadm** [comment]
No success with --authVersion=aws2 as well.
S3fs, s3cmd, minio-client works smoothly, so I believe I am missing some specific configuration required for s3backer.

**Comment by archiecobbs** [comment]
Should be fixed by 7da39b7.
